### ISSUE TITLE
Can't access vitess by mysql protocol

### ISSUE THREAD

**Issue by retigrid** [vitessio/vitess#3884] opened 2018-05-02 03:33 UTC
I used several analysis tools(metabase, bigquery etc) to test connectivity with vitess. My DB's keyspace is metering. Nevertheless, when connecting to a DB, the name of the DB is entered as metering, but the actual database of mysql is set to vt_metering, so I think it is not possible to show tables.
I attached log from vttablet when I access vitess.

I0501 03:32:25.874896       1 tabletserver.go:1391] Unknown database 'metering' (errno 1049) (sqlstate 42000) during query: SHOW FULL TABLES FROM `metering` LIKE '%!'(MISSING), CallerID: reti_dev: Sql: "SHOW FULL TABLES FROM `metering` LIKE '%!'(MISSING)", BindVars: {}
I0501 03:32:36.178874       1 tabletserver.go:1391] Unknown database 'metering' (errno 1049) (sqlstate 42000) during query: SHOW FULL TABLES FROM `metering` LIKE '%!'(MISSING), CallerID: reti_dev: Sql: "SHOW FULL TABLES FROM `metering` LIKE '%!'(MISSING)", BindVars: {}

**Comment by dweitzman** [comment] 2018-05-02 06:30
I think this may be a dupe of https://github.com/vitessio/vitess/issues/3578

**Comment by sougou** [comment] 2018-05-03 00:43
Yes. I've tagged it as dup.

**Closed by sougou** 2018-05-03 00:43 UTC
Labels: P3, Status: Duplicate, Type: Feature Request
