### ISSUE TITLE
bootstrap.sh does not check and report if required govendor is missing.

### ISSUE THREAD

**Issue by sjmudd** [vitessio/vitess#4012] opened 2018-06-08 14:02 UTC
#### Overview of the Issue

Following the docs on building vitess I see that It runs but fails here:

```
Updating govendor dependencies...
./bootstrap.sh: line 276: govendor: command not found
ERROR: Failed to download/update dependencies with govendor. Please re-run bootstrap.sh in case of transient errors.```
I’ll make an issue for that so it won’t get forgotten.
```

This is after downloading most of the dependencies.

#### Reproduction Steps

See above.

#### Binary version

HEAD from master branch as of 2018-06-08.

#### Operating system and Environment details

I'm trying to do repeatable rpm builds for Vitess.
On CentOS 7.

#### Suggestion to fix

* add a step to the documentation to ensure that govendor is installed (and show how to install might be good). I can do that but it's good for others to know. Saves them searching.
* check earlier in the script that this is missing so the build process will run to completion once this is fixed and the error is reported immediately.

Alternatively make the `bootstrap.sh` script download and build `govendor`  if it's missing.

**Comment by michael-berlin** [comment] 2018-06-11 17:01
In general, I would prefer not to list govendor as dependency as well because we already install it for the user. Otherwise, our list of dependencies is going to become out of control. Plus, it's hard to maintain this list in the documentation and keep it up to date.

Just before the step which failed for you, bootstrap.sh tries to install "govendor". If that fails, bootstrap.sh fails overall.

See: https://github.com/vitessio/vitess/blob/master/bootstrap.sh#L261

Therefore, you should not have ended up in this situation in the first place.

Given that, let's focus on fixing that bug.

Simon, can you reproduce the issue? How come you got past the `go get -u $gotools` command?

**Comment by sjmudd** [comment] 2018-06-11 21:02
Hi. I have to see what I was doing. I think that basically my `PATH` did not find it. So as I was looking to automate the build process (as I want to build rpms for the binaries) and the web tree I added something which fixed this for me which was to do the following:

```
       if govendor=`which govendor`; then
                echo "OK: found govendor: $govendor"
        else
                echo "Can not find govendor, so building it..."
                export GOPATH=$WORKSPACE
                go get -u github.com/kardianos/govendor
                echo "install completed"
                echo "looking for govendor..."
                govendor=$(find $PWD | grep bin/govendor)
                if [ -n "$govendor" ]; then
                        export PATH="$PATH:$(dirname $govendor)"
                fi
        fi
```

So following the instructions alone I had not set `GOPATH` and `PATH` did not include the location of `govendor`. Thus fixing that would resolve the issue.  The "shell snippet" above is used prior to calling bootstrap.sh and resolves the issue for me. Ideally it shouldn't be necessary and bootstrap.sh  should probably do something equivalent.

(that or I'm doing something wrong).

I hope that clarifies.

**Comment by sjmudd** [comment] 2018-06-13 21:34
I've just tried this slightly differently on a home computer (also running CentOS 7) and I get this:
```
(part of an rpm build)
...
installing Selenium latest
New python executable in /home/sjmudd/RPM/TMP/vitess-v2.2.0.rc.1.20180613.095107/dist/selenium/bin/python
Installing setuptools, pip, wheel...done.
Collecting selenium
  Downloading https://files.pythonhosted.org/packages/57/bc/17164fd471ccdf0df3a992c710c0c3c47743462ff41ab72a02c6ede96e90/selenium-3.12.0-py2.py3-none-any.whl (946kB)
    100% |################################| 952kB 900kB/s
Installing collected packages: selenium
Successfully installed selenium-3.12.0
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
installing chromedriver 2.25
Installing dev tools with 'go get'...
Updating govendor dependencies...
./bootstrap.sh: line 276: govendor: command not found
ERROR: Failed to download/update dependencies with govendor. Please re-run bootstrap.sh in case of transient errors.
error: Bad exit status from /home/user/RPM/TMP/rpm-tmp.LTmz49 (%build)


RPM build errors:
    Bad exit status from /home/sjmudd/RPM/TMP/rpm-tmp.LTmz49 (%build)
$ echo $PATH
/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/user/.local/bin:/home/user/bin
$ rpm -q centos-release
centos-release-7-4.1708.el7.centos.x86_64
$ set | grep GO
```

So to me if GOPATH is not set and PATH does not include the right directories then even if you pull down govendor and build it you won't find it later. Consequently clarifying what you expect in `PATH` or `GOPATH` seems like a good idea. Perhaps you can see your own build environment and see if GOPATH or PATH is set and if they are how they're set as that may give me a clue as to what to change to make this work.

**Comment by hellracer** [comment] 2018-11-18 22:10
This is happening also in Ubuntu 18.04 but not on 16.04 on my limited testing

**Comment by morgo** [comment] 2019-11-13 16:52
I am going to close this as obsolete. We switched from govendor to go modules.

**Closed by morgo** 2019-11-13 16:52 UTC
Labels: P3, Type: Bug
