### ISSUE TITLE
query will hang there when delete pod(or pod is broken)

### ISSUE THREAD

**Issue by Johnny-Three** [vitessio/vitess#5475] opened 2019-11-27 02:12 UTC
#### Overview the issue

Read from replica type role instance.
we have found that if a pod was broken for somehow reason.
the QPS will not run onto the healthy replica node for nearly 8 minutes
(The 8 minutes is what we observed from the online environment,
it may also because of the app set connection broken time or somehow.
actually i can not reproduce the scene that it will continue the query after hanging for 8 minutes unless application reconnect)

#### Reproduction Steps
Based on Branch 3.0
1. prepared a tmp.txt written for 200 lines:

    ```sql
    select * from message;select sleep(3);
    ```
2. unsharded keyspace with 2 or more replicas
3. mysqlclient connect to a vtgate by using replica account
4. source tmp.txt
5. query hangs for a very long time and vtgate withretry not happen
6. the query brokes

**Comment by gedgar** [comment] 2021-09-23 01:11
Closing this issue for now as I'm unable to reproduce this issue on 12.0.0-SNAPSHOT (b04726d); I'm able to source `tmp.txt` without issue and am seeing traffic being routed appropriately to other replicas during some chaos testing. 

@Johnny-Three, please feel free to reopen this if you're still encountering this problem. Thanks!

**Closed by gedgar** 2021-09-23 01:11 UTC
Labels: Type: Bug
