### ISSUE TITLE
Local setup dies after waiting for mysql.sock

### ISSUE THREAD

**Issue by kushalkh** [vitessio/vitess#5182] opened 2019-09-11 20:59 UTC
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

I followed the steps on "Run Vitess Locally" to set things up for tests. I'm running MariaDB 10.2 (also tried with MariaDB 10.4) and running into issues when executing ./101_initial_cluster.sh

The MySQL initialization fails,  i guess it's not able to create the socket file.

#### Reproduction Steps

Following instructions on "Run Vitess Locally" and execute ./101_initial_cluster.sh

#### Operating system and Environment details

OS, Architecture, and any other information you can provide
about the environment.

- Operating system (output of `cat /etc/os-release`): 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel version (output of `uname -sr`):
Linux 3.10.0-957.27.2.el7.x86_64

- Architecture (output of `uname -m`):
x86_64

#### Log Fragments

Log file created at: 2019/09/11 16:46:14
Running on machine: replictest
Binary: Built with gc go1.11.4 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0911 16:46:14.809948   28654 dbconfigs.go:275] DBConfigs: {
  "Conn": {
    "host": "",
    "port": 0,
    "uname": "vt_dba",
    "pass": "****",
    "dbname": "",
    "unix_socket": "/root/vtdataroot/vt_0000000100/mysql.sock",
    "charset": "utf8",
    "flags": 0,
    "ssl_ca": "",
    "ssl_ca_path": "",
    "ssl_cert": "",
    "ssl_key": "",
    "server_name": "",
    "DeprecatedDBName": "",
    "DisableClientDeprecateEOF": false
  },
  "Users": {
    "dba": "vt_dba"
  }
}
I0911 16:46:14.810955   28654 mysqld.go:537] execCmd: /usr/sbin/mysqld /usr/sbin/mysqld [--version]
I0911 16:46:14.929104   28654 mysqld.go:551] execCmd: /usr/sbin/mysqld output: /usr/sbin/mysqld  Ver 10.2.27-MariaDB for Linux on x86_64 (MariaDB Server)
I0911 16:46:14.929154   28654 mysqld.go:127] Using flavor: mariadb, version: {10 2 27}
I0911 16:46:14.929178   28654 mysqld.go:303] Mysqld.Start(1568234774): No mysqld_start hook, running mysqld_safe directly
I0911 16:46:14.929192   28654 mysqld.go:333] Mysqld.Start(1568234774) &exec.Cmd{Path:"/usr/bin/mysqld_safe", Args:[]string{"/usr/bin/mysqld_safe", "--defaults-file=/root/vtdataroot/vt_0000000100/my.cnf", "--basedir=/usr"}, Env:[]string{"LD_LIBRARY_PATH=/usr/lib/mysql"}, Dir:"/usr", Stdin:io.Reader(nil), Stdout:io.Writer(nil), Stderr:io.Writer(nil), ExtraFiles:[]*os.File(nil), SysProcAttr:(*syscall.SysProcAttr)(nil), Process:(*os.Process)(nil), ProcessState:(*os.ProcessState)(nil), ctx:context.Context(nil), lookPathErr:error(nil), finished:false, childFiles:[]*os.File(nil), closeAfterStart:[]io.Closer(nil), closeAfterWait:[]io.Closer(nil), goroutine:[]func() error(nil), errch:(chan error)(nil), waitDone:(chan struct {})(nil)}
I0911 16:46:14.929489   28654 mysqld.go:400] Waiting for mysqld socket file (/root/vtdataroot/vt_0000000100/mysql.sock) to be ready...
I0911 16:46:15.077176   28654 mysqld.go:351] Mysqld.Start(1568234774) stdout: 190911 16:46:15 mysqld_safe Logging to '/root/vtdataroot/vt_0000000100/error.log'.
I0911 16:46:15.100676   28654 mysqld.go:351] Mysqld.Start(1568234774) stdout: 190911 16:46:15 mysqld_safe Starting mysqld daemon with databases from /root/vtdataroot/vt_0000000100/data
I0911 16:46:15.223584   28654 mysqld.go:364] Mysqld.Start(1568234774) exit: <nil>
E0911 16:51:15.041352   28654 mysqlctl.go:254] failed start mysql: deadline exceeded waiting for mysqld socket file to appear: /root/vtdataroot/vt_0000000100/mysql.sock

**Comment by parthibd** [comment] 2019-09-14 12:55
The same thing is happening to me on mysql 5.7. The local installation examples don't work at all. It gives me mysql ld errors

**Comment by morgo** [comment] 2019-09-15 04:45
This appears to be caused by running the local example as the **root user**. Note the filesystem path:
```
/root/vtdataroot/vt_0000000100/data
```

The `mysqld` binary refuses to execute as root. There will be an error in `/root/vtdataroot/vt_0000000100/` such as this one:
```
2019-08-29T23:58:07.709723Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2019-08-29T23:58:07.710629Z 0 [Note] mysqld (mysqld 5.7.27) starting as process 4614 ...
2019-08-29T23:58:07.711484Z 0 [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!

2019-08-29T23:58:07.711500Z 0 [ERROR] Aborting

2019-08-29T23:58:07.711510Z 0 [Note] Binlog end
2019-08-29T23:58:07.711532Z 0 [Note] mysqld: Shutdown complete
```

**Comment by kushalkh** [comment] 2019-09-16 21:30
@morgo 
Thanks for the feedback.

Do you recommend running it as any other user but root? Or as mysql?
Also, i installed MariaDB as user root, so not sure if that impacts anything.

Tried it as another user and here's the error in /home/vitessuser/vtdataroot/vt_0000000100/error.log now:


190916 15:55:48 mysqld_safe Starting mysqld daemon with databases from /home/vitessuser/vtdataroot/vt_0000000100/data
190916 15:55:48 [Note] //sbin/mysqld (mysqld 10.0.38-MariaDB) starting as process 8833 ...
190916 15:55:48 [ERROR] Can't find messagefile '/share/mysql/errmsg.sys'
190916 15:55:48 [ERROR] Aborting

190916 15:55:48 [Note]
190916 15:55:48 mysqld_safe mysqld from pid file /home/vitessuser/vtdataroot/vt_0000000100/mysql.pid ended

Any idea why it's looking for /share/mysql/errmsg.sys in that location ?

**Comment by morgo** [comment] 2019-09-19 20:46
> Do you recommend running it as any other user but root? Or as mysql?

Any other user but root.

> Any idea why it's looking for /share/mysql/errmsg.sys in that location ?

It might be related to the basedir argument uses when starting mariadb. I would expect that the file is actually in `/usr/share/mysql/*`. You could try working around it with a symlink.

**Comment by morgo** [comment] 2019-10-26 02:46
MariaDB 10.4 is known not to work. I have created https://github.com/vitessio/vitess/issues/5362 to track.

An enhancement to cat mysql's error log was recently merged, which should make these issues easier to debug: https://github.com/vitessio/vitess/pull/5323

**Comment by morgo** [comment] 2019-11-09 20:26
Stronger protection against running as root has been added to the master branch. As such, I am going to close this issue for now.

Please free to followup if you have any further questions. Thanks!

**Closed by morgo** 2019-11-09 20:26 UTC
Labels: Type: Question
