### ISSUE TITLE
tpcc test vitess problem

### ISSUE THREAD

**Issue by ResearchRogerPan** [vitessio/vitess#5812] opened 2020-02-11 13:09 UTC
tpcc test vitess problem: tpcc start reports fatal error: concurrent map read and map write

Can you give some suggestions on tpcc test

**Comment by saifalharthi** [comment] 2020-02-12 05:21
Hello @ResearchRogerPan , I am really interested to know what you are using for your TPC-C test and what are the parameters being used. Can you post them? that would help a lot.

**Comment by ResearchRogerPan** [comment] 2020-02-14 09:11
Hello, I use tpcc to test the problems encountered by vitess. I want to ask if I can give test suggestions, such as cluster configuration. I have not encountered map problems recently, and I will submit it later.

The problem now is this, I imported a single-line insert statement exported from mysql into the vitss cluster and encountered this error:< can not a new thread, if you are not out of avaiable memory, you can consult the manual for a possible OS-dependent bug>. In fact, the insertion of a single statement does not have concurrency, and I hope to get a solution. In addition, I especially want to be able to give tpcc test recommendations or tpcc tools.
Thanks.

**Comment by GuptaManan100** [comment] 2021-10-18 09:39
TPCC tests are now being run everyday as a cron job in Vitess now in the project [arewefastyet](https://github.com/vitessio/arewefastyet). I am closing this for now, please reopen if the issue is still there

**Closed by GuptaManan100** 2021-10-18 09:39 UTC
Labels: P3, Type: Bug, Component: Cluster management
