### ISSUE TITLE
gRPC interface to `vtctl` to use

### ISSUE THREAD

**Issue by guidoiaquinti** [vitessio/vitess#5980] opened 2020-03-27 09:15 UTC
Pulling this out from an internal conversation

#### Feature Description
Provide well-defined grpc interface to `vtctl` to use

#### Use Case(s)
We were looking at moving some of our operational tooling for Vitess to go, and we noticed that there isn’t a “true” interface into the vtctld in the protobuf definition. While there is a grpc endpoint, it’s not well defined, as it’s mainly a passthrough to all of the different vtctld methods.

For example, instead of there being a `FindAllShardsInKeyspace` endpoint, we instead call `vtctlclient.ExecuteVtctlCommand(vtctldata.ExecuteVtctlCommandRequest{Args: []string{"FindAllShardsInKeyspace", "keyspace_name"}})` and then parse the response into our own user-defined structs, instead of having structs in the `.pb.go` file that we can use instead.

Quoting @sougou 
> I've been having similar thoughts, but right now is not a good time. The deprecation of SBR, v2 and old resharding workflows are going to drastically change the list of commands available through vtctld. We can look at doing this after all this stabilizes.

**Comment by derekperkins** [comment] 2020-03-27 13:51
We found this out too and it makes tooling more difficult. Having a real API will also make the new UI much easier to build.

**Comment by ajm188** [comment] 2021-09-09 17:14
This is a dupe of https://github.com/vitessio/vitess/issues/7058, I'm going to close this one.

**Closed by ajm188** 2021-09-09 17:14 UTC
Labels: Type: Feature Request, P3, Component: Cluster management
