### ISSUE TITLE
Vreplication fails when gtid_executed is > 10000 bytes

### ISSUE THREAD

**Issue by gtowey** [vitessio/vitess#8612] opened 2021-08-09 22:52 UTC
#### Overview of the Issue

Vreplication fails with `unable to parse mysql 5.6 GTID set` when the length of the gtid_executed string exceeds the column size of 10,000 bytes.

__Note__: This is a pretty simple fix and I can submit a PR along with this issue. 

#### Reproduction Steps

1. Create a large gtid_executed set by performing many replication changes across many mysql instances with different server UUIDs
1. Run a `Reshard` workflow
1. View the error in vreplication on the chosen tablet's status page.

#### Operating system and Environment details

n/a

**Comment by shlomi-noach** [comment] 2021-08-29 13:59
@gtowey I assume the problem is here:

https://github.com/vitessio/vitess/blob/600cca789bad1fb5f312f4666b1678ba926608b6/go/vt/binlog/binlogplayer/binlog_player.go#L544-L545

?

If you are able to, we welcome a PR to increase this length.

**Comment by mattlord** [comment] 2024-09-25 16:30
I'm going to close this as done for now. Please note that we've since added compression for this value as well: https://github.com/vitessio/vitess/pull/7877

**Closed by mattlord** 2024-09-25 16:30 UTC
Labels: Type: Bug, Component: VReplication
