### ISSUE TITLE
Feature Request: better queries for reshard operations

### ISSUE THREAD

**Issue by ejortegau** [vitessio/vitess#11996] opened 2022-12-20 12:12 UTC
### Feature Description

Queries for reshard opetations can be very expensive/inefficient. We are currently suffering from it as described below. We have a table like this:

```sql
CREATE TABLE `our_table` (
  `col01` bigint(20) unsigned NOT NULL,
  `col02` bigint(20) unsigned NOT NULL,
  `col03` bigint(20) unsigned NOT NULL,
  `col04` bigint(20) unsigned NOT NULL,
  `col05` bigint(20) unsigned NOT NULL,
  `col06` int(10) unsigned NOT NULL,
  `col07` varchar(255) NOT NULL,
  `col08` tinyint(3) unsigned NOT NULL,
  `col09` bigint(20) unsigned NOT NULL,
  `col10` bigint(20) unsigned NOT NULL,
  `col11` bigint(20) unsigned NOT NULL,
  `col12` bigint(20) unsigned NOT NULL,
  `col13` bigint(20) unsigned NOT NULL,
  `col14` bigint(20) unsigned NOT NULL,
  `col15` mediumtext NOT NULL,
  `col16` longblob,
  `col17` blob,
  `col18` varchar(255) NOT NULL,
  `col19` tinyint(3) unsigned NOT NULL,
  `col20` tinyint(3) unsigned NOT NULL,
  PRIMARY KEY (`col01`,`col02`,`col03`),
  KEY `col14` (`col14`),
  KEY `col05` (`col02`,`col05`),
  KEY `col13` (`col13`),
  KEY `latest_counted` (`col01`,`col02`,`col20`,`col03`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPRESSED
```

with a `hash` vindex in column `col02`.  We are trying to reshard one of our existing shards  (66-67) into four smaller ones
(6600-6640, 6640-6680, 6680-66c0, 66c0-6700). The reshard operation generates queries in the source shard of the form:

```sql
select col01, col02, ... col20 from our_table where (col01 = 3557174030 and col02 = 15925516356 and col03 > 1460011502000027) or (col01 = 3557174030 and col02 > 15925516356) or (col01 > 3557174030) order by col01, col02, col03
```
The query comes from [`rowStreamer.buildSelect()`](https://github.com/vitessio/vitess/blob/a6ab8a21c52fb578faf5d61bf4bb11c351a03a4f/go/vt/vttablet/tabletserver/vstreamer/rowstreamer.go#L231), and  has the following explain plan:

```sql
*************************** 1. row ***************************
            id: 1 
    select_type:  SIMPLE 
          table: our_table 
     partitions: NULL 
           type: range 
  possible_keys: PRIMARY,col05,latest_counted 
            key: PRIMARY 
        key_len: 24 
            ref: NULL 
           rows: 1931856636 
       filtered: 100.00 
          Extra: Using where 
1 row in set, 1 warning (0.00 sec) 
```

As shown by the explain output, the query needs to read a very large number of rows. For context, a `count(*)` for the shard being resharded yields 3362880723 rows. Therefore, it can take a very long time to execute, potentially exceeding network timeouts both at the vitess and mysql levels. The only workaround is to configure higher values for them - different from what is usually used in production. Plus finding the right values can change from shard to shard.

It would likely be better to issue multiple  queries for small batches of rows to copy like this one:

```sql
select col01, col02, ... col20 from our_table where (col01 = 3557174030 and col02 = 15925516356 and col03 > 1460011502000027) limit 1000 -- or some other fixed batch size
```
Only if that gives less than the number of rows provided in the limit, try to run:
```sql
select col01, col02, ... col20 from our_table where (col01 = 3557174030 and col02 > 15925516356) limit 1000
```
And, again, only if that again yields less than the provided limit number of rows, try:
```sql
select col01, col02, ... col20 from our_table where (col01 > 3557174030) limit 1000
```
Each one of the queries above reads a drastically smaller number of rows. Also, no ordering condition needs to be specified due to the fact that InnoDB clustered index guarantees that rows are produced in order of the columns of the PK. 

Each batch of results of the queries above could be processed (i.e. copied to the target shard, updating the vreplicaiton status with the latest PK copied), and the next batch should be tried until the result of 

```sql
select col01, col02, ... col20 from our_table where (col01 > vale_of_last_successfully_copied_row_first_pk_field) limit 1000
```
produces zero rows.

The above should significantly speed up the copy phase of vreplication.

### Use Case(s)

This should benefit the resharding of large tables with multi-column PKs.

**Comment by maksimov** [comment] 2022-12-20 13:32
Related/duplicate of #10012

**Comment by mattlord** [comment] 2023-08-31 02:48
I'm going to close this for now as a duplicate of https://github.com/vitessio/vitess/issues/10012, which was fixed. 

If you feel that I'm missing something here please let me know and we can re-open it. Thanks!

**Closed by mattlord** 2023-08-31 02:48 UTC
Labels: Type: Feature Request, Component: VReplication
