### ISSUE TITLE
Failing Orchestrator Integration in backups disabled case

### ISSUE THREAD

**Issue by lokanadhamm** [vitessio/vitess#4006] opened 2018-06-06 15:20 UTC
local_metadata table will get populated only if we enable backup. If we disable the backup this table will be empty.
As, this table data will be used used by orchestrator for getting tablet_alias and shard_alias, in backup disabled case orchestrator not able to do reparenting.
ExternallyReparent command is failing, because its getting empty tablet alias from orchestrator.

**Comment by derekperkins** [comment] 2018-06-06 17:44
I think this is a symptom of #3753

**Comment by derekperkins** [comment] 2018-06-06 17:45
And may be a duplicate of https://github.com/vitessio/vitess/issues/2451

**Comment by derekperkins** [comment] 2018-07-30 21:59
closing in favor of #4115

**Closed by derekperkins** 2018-07-30 21:59 UTC
Labels: P3, Type: Feature Request
