### ISSUE TITLE
Bug Report: Prepared statement fails with more than `65,528` parameters

### ISSUE THREAD

**Issue by frouioui** [vitessio/vitess#12333] opened 2023-02-13 18:55 UTC
### Overview of the Issue

Original issue can be found in https://github.com/planetscale/discussion/discussions/371.

### Reproduction Steps

See https://github.com/planetscale/discussion/discussions/371.

### Binary Version

```sh
main, release-16.0, possibly release-15.0 too
```

### Operating System and Environment details

```sh
n/a
```

**Comment by harshit-gangal** [comment] 2023-03-20 07:31
Closing as the issue is fixed

**Closed by harshit-gangal** 2023-03-20 07:31 UTC
Labels: Type: Bug, Component: Query Serving
