### ISSUE TITLE
Feature Request: Allow new databases/keyspaces to run in `foreignKeyMode=managed` by default (in `vttestserver`)

### ISSUE THREAD

**Issue by janpio** [vitessio/vitess#14661] opened 2023-12-02 08:19 UTC
### Feature Description

Currently one has to define all the keyspaces/databases for `vttestserver` before starting the container, as any `CREATE DATABASE` will just create a `foreignKeyMode=unmanaged` keyspace/database, and there is no way to change it at runtime either.

It would be great if one could configure `vttestserver` to default to `managed` instead.

### Use Case(s)

We want to test our Prisma ORM against Vitess, with `foreignKeyMode=managed`. Our test suite works by creating a lot of databases for test isolation. That means we can unfortunately not gather or provide the list of all keyspaces/databases prior to starting the Docker container of `vttestserver`. (The list might even become too long for an env var, in our test setup.)

(Related question on how to confirm the mode functionally, not via `SHOW KEYSPACES;`: https://github.com/vitessio/vitess/issues/14660)

**Comment by GuptaManan100** [comment] 2023-12-04 03:42
After you have created a database, you can always run [ApplyVschema](https://vitess.io/docs/18.0/reference/programs/vtctldclient/vtctldclient_applyvschema/) command with a new Vschema that specifies the foreign key mode to `managed`

**Comment by GuptaManan100** [comment] 2023-12-05 06:44
I just verified, it currently does't work with vttestserver, because of the hard-coded bind address it provides to vtcombo. I am working on fixing this. Work in progress PR - https://github.com/vitessio/vitess/pull/14665

**Comment by GuptaManan100** [comment] 2023-12-05 08:58
I was able to test my changes and make the required adjustments to get vtctdclient commands to work with vttestserver - https://github.com/vitessio/vitess/pull/14665

**Comment by GuptaManan100** [comment] 2023-12-05 09:00
@janpio once that PR is merged, I believe you will be able to use it. I have added all the steps I followed to create a new database in vttestserver and then change its foreign key mode to managed. Please follow those steps and it should work as intended.

**Closed** 2023-12-05 14:52 UTC
Labels: Type: Feature Request, Component: Query Serving
