### ISSUE TITLE
'USE' doesn't return an error if a keyspace doesn't exist

### ISSUE THREAD

**Issue by guidoiaquinti** [vitessio/vitess#3060] opened 2017-08-14 13:52 UTC
Right now if we execute a `USE` against a keyspace/db that doesn't exist, we don't return any error to the client (we only do that after failing a query): 

```
mysql> use this_db_doesnt_exist;
Database changed
```
`vtgate` only logs an error: `E0814 13:47:41.481496   24441 resilient_srv_topo_server.go:280] WatchSrvKeyspace failed for test/this_db_doesnt_exist: node doesn't exist`

```
mysql> show tables;
ERROR 1105 (HY000): vtgate: http://vitess:15001/: keyspace this_db_doesnt_exist fetch error: node doesn't exist
```

My proposal is to align Vitess to what MySQL already offers:
```
mysql> use this_db_doesnt_exist;
ERROR 1049 (42000): Unknown database 'this_db_doesnt_exist'
```

**Comment by sougou** [comment] 2017-08-14 21:04
This sounds good.

**Comment by giaquinti** [comment] 2017-08-28 11:17
Adding a minor note here to support as well system schemas:

```
mysql> use information_schema;
Database changed

mysql> SHOW TABLES FROM `information_schema`;
ERROR 1105 (HY000): vtgate: http://vitess:15001/: keyspace information_schema fetch error: node doesn't exist
```
the last query works fine if `use information_schema;` is skipped

**Comment by sougou** [comment] 2017-09-03 14:54
We could add support for `use <sys-schema>` construct, but there are not many use cases right now. I believe most use cases want to `use <keyspace>` and `select ... from information_schema.<table>`.

It will become very powerful if vitess could show a consolidated view. Then this will become a powerful feature. It's something we can keep in mind.

**Comment by morgo** [comment] 2019-11-04 21:02
I think this is important to fix, because in general Vitess is quite strict about how it handles edge-cases. This makes it easier to validate that it is working correctly (vs. MySQL's traditional behavior of parse but ignore etc.)

**Comment by morgo** [comment] 2019-11-12 23:22
There is another use-case why this is important. In MySQL (depending on platform) the schema name may be case-insensitive. So when you move to vitess, you may get this error.. which won't make sense to you. The semantics are much clearer if the initial selecting of the database fails.

**Comment by llibdude** [comment] 2019-11-14 15:44
Ok, I see. Because database names are case sensitive in vitess, we should always show them in the proper case so people don't think it's okay to use incorrect casing?

**Comment by llibdude** [comment] 2019-11-14 15:59
I had commented on the wrong issue and have deleted the message. Please disregard :)

**Comment by saifalharthi** [comment] 2020-03-24 18:05
I was looking debugging this issue and looking at query logs , this query does not invoke `handleUse` in the executor. However, I think mysql client sends a `com_init_db`and at this time we don't process it.

**Comment by deepthi** [comment] 2020-03-25 21:05
@saifalharthi can you document the full list of commands generated by `use`?

**Comment by saifalharthi** [comment] 2020-03-30 19:14
These are the commands I logged 
```
select @@version_comment limit 1
SELECT DATABASE()
show databases
show tables
```

**Comment by harshit-gangal** [comment] 2020-04-28 13:27
Can this be closed? This is fixed

**Comment by deepthi** [comment] 2020-04-28 15:39
> Can this be closed?

do you know which PR fixed it? Then we can refer to it here and close it.

**Comment by harshit-gangal** [comment] 2020-04-28 16:18
If someone issues use <target>. It exists.
It is not implemented for ComInitDB call from mysql driver.

**Comment by sougou** [comment] 2020-04-28 17:38
I don't think it's fixed. We might even have a regression of some sort. From the local example:

```
mysql> show databases;
+-----------+
| Databases |
+-----------+
| commerce  |
+-----------+
1 row in set (0.00 sec)

mysql> use aaa
Database changed
mysql> select * from product;
Empty set (0.00 sec)

mysql> 
```

**Comment by deepthi** [comment] 2020-04-28 20:43
That _is_ a regression, it used to error out on the select, now it silently uses *a* keyspace.

**Closed** 2020-05-07 16:49 UTC
Labels: P2, Type: Bug
