### ISSUE TITLE
Uncaught panic: sync: WaitGroup is reused before previous Wait has returned

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#5196] opened 2019-09-17 10:38 UTC
This looks similar to #3628, #4806 and #3643, but still doesn't appear to be fixed. This prevented my master from restarting and reparenting, causing the shard to be unavailable. I'm running from master cut around Sept 1, 2019.

```
E0917 04:30:57.989524       1 tabletenv.go:135] Uncaught panic:
sync: WaitGroup is reused before previous Wait has returned
/usr/local/go/src/runtime/panic.go:513 (0x42be28)
/usr/local/go/src/sync/waitgroup.go:132 (0x4730bc)
/vt/src/vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:642 (0xc216dd)
/vt/src/vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:621 (0xc21519)
/vt/src/vitess.io/vitess/go/vt/vttablet/tabletserver/tabletserver.go:719 (0xc3f3e9)
/usr/local/go/src/runtime/asm_amd64.s:1333 (0x45bed0)
```

**Comment by deepthi** [comment] 2022-02-07 22:53
Ran into this today, and I think that gives us a repro.
```
E0207 22:40:00.913783       1 tabletserver.go:1503] immediate error from server errorCode=1040 errorMsg=Too many connections (errno 2012) (sqlstate HY000)
```
The queryserver-config-pool-size value was set higher than mysql's max_connections.

**Comment by GuptaManan100** [comment] 2022-02-09 07:25
Me and @harshit-gangal tried to reproduce this by reducing the mysql max connections to 20. We were able to see the same error message but we didn't see any panic. @deepthi Could you share the logs which contain the panic?

**Comment by deepthi** [comment] 2022-02-09 20:42
What I have is https://planetscale.slack.com/archives/C02NHUSBW1H/p1644273656833539
You probably need to have continuous traffic to reproduce? Did you have that?

**Comment by erikhalperin-hub** [comment] 2023-09-20 16:55
@GuptaManan100 I think we ran into this as well - here's a [gist](https://gist.github.com/erikhalperin-hub/8e8ec333ceea13aa418a9d04efa8dc61) of the tablet logs leading up to the panic (with some sanitation, for instance changing a sql query to <sql>). Are these helpful? Let me know if there's anything else I could send you

Some pointers - 
The tablet starts killing queries that ran too long. Hundreds more queries are killed
```
2023-09-05T16:16:50.995265919Z I0905 16:16:50.995219       2 dbconn.go:348] Due to context canceled, elapsed time: 1.00005581s, killing query ID 376286 <sql>
```
The tablet shuts down the query service because max_user_connections is full
```
2023-09-05T16:16:51.617088207Z E0905 16:16:51.617085       2 state_manager.go:284] Cannot connect to MySQL, shutting down query service: User <user> already has more than 'max_user_connections' active connections (errno 1203) (sqlstate 42000)
```
The panic:
```
2023-09-05T16:39:54.440227197Z panic: sync: WaitGroup is reused before previous Wait has returned
```

**Comment by GuptaManan100** [comment] 2023-09-25 08:36
@erikhalperin-hub Thank you for providing the logs. COuld I ask what version of Vitess are you running?

**Comment by erikhalperin-hub** [comment] 2023-09-25 12:47
We're running Vitess 14 plus some patches

**Comment by GuptaManan100** [comment] 2024-03-26 07:45
This has been fixed by the changes in https://github.com/vitessio/vitess/pull/14924. The issue was actually duplicated at https://github.com/vitessio/vitess/issues/14933

**Closed by GuptaManan100** 2024-03-26 07:45 UTC
Labels: Type: Bug, Status: Unable to Reproduce, Component: TabletManager
