### ISSUE TITLE
SwitchWrites after MoveTables where source keyspace is using FilePos will fail unless MoveTables VReplication streams are from source keyspace primary tablet

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#7317] opened 2021-01-19 01:01 UTC
This has probably been an issue all along, but tested against 9.0 RC1.

I used `dbdeployer` to setup:

  * A local set of 3 database instances, one master, 2 replicas.  Using FilePos replication (i.e. `gtid_mode=OFF`).
  * I then stood up an unsharded Vitess 9.0 RC1 keyspace using MySQL 8.0 called `keyspace1`  (the target for the `MoveTables`)
  * I stood up Vitess 9.0 RC1 tablets in front of the external 3 database instances.  This keyspace is called `keyspace3` (the source for the `MoveTables`).

State of the external master:

```
$ ./use_all_masters "show master status\G"
*************************** 1. row ***************************
             File: mysql-bin.000001
         Position: 328858
     Binlog_Do_DB:
 Binlog_Ignore_DB:
Executed_Gtid_Set:
```

State of the external replicas:

```
$ ./use_all_slaves "show master status\G"
server: 1
*************************** 1. row ***************************
             File: mysql-bin.000001
         Position: 326452
     Binlog_Do_DB:
 Binlog_Ignore_DB:
Executed_Gtid_Set:
server: 2
*************************** 1. row ***************************
             File: mysql-bin.000001
         Position: 326452
     Binlog_Do_DB:
 Binlog_Ignore_DB:
Executed_Gtid_Set:

$ ./use_all_slaves "show slave status\G"
server: 1
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: 127.0.0.1
                  Master_User: rsandbox
                  Master_Port: 20617
                Connect_Retry: 60
              Master_Log_File: mysql-bin.000001
          Read_Master_Log_Pos: 328858
               Relay_Log_File: mysql-relay.000002
                Relay_Log_Pos: 329072
        Relay_Master_Log_File: mysql-bin.000001
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 328858
              Relay_Log_Space: 329276
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: 0
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 100
                  Master_UUID: 00020617-1111-1111-1111-111111111111
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for more updates
           Master_Retry_Count: 86400
                  Master_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set:
            Executed_Gtid_Set:
                Auto_Position: 0
         Replicate_Rewrite_DB:
                 Channel_Name:
           Master_TLS_Version:
       Master_public_key_path:
        Get_master_public_key: 1
            Network_Namespace:

server: 2
*************************** 1. row ***************************
               Slave_IO_State: Waiting for master to send event
                  Master_Host: 127.0.0.1
                  Master_User: rsandbox
                  Master_Port: 20617
                Connect_Retry: 60
              Master_Log_File: mysql-bin.000001
          Read_Master_Log_Pos: 328858
               Relay_Log_File: mysql-relay.000002
                Relay_Log_Pos: 329072
        Relay_Master_Log_File: mysql-bin.000001
             Slave_IO_Running: Yes
            Slave_SQL_Running: Yes
              Replicate_Do_DB:
          Replicate_Ignore_DB:
           Replicate_Do_Table:
       Replicate_Ignore_Table:
      Replicate_Wild_Do_Table:
  Replicate_Wild_Ignore_Table:
                   Last_Errno: 0
                   Last_Error:
                 Skip_Counter: 0
          Exec_Master_Log_Pos: 328858
              Relay_Log_Space: 329276
              Until_Condition: None
               Until_Log_File:
                Until_Log_Pos: 0
           Master_SSL_Allowed: No
           Master_SSL_CA_File:
           Master_SSL_CA_Path:
              Master_SSL_Cert:
            Master_SSL_Cipher:
               Master_SSL_Key:
        Seconds_Behind_Master: 0
Master_SSL_Verify_Server_Cert: No
                Last_IO_Errno: 0
                Last_IO_Error:
               Last_SQL_Errno: 0
               Last_SQL_Error:
  Replicate_Ignore_Server_Ids:
             Master_Server_Id: 100
                  Master_UUID: 00020617-1111-1111-1111-111111111111
             Master_Info_File: mysql.slave_master_info
                    SQL_Delay: 0
          SQL_Remaining_Delay: NULL
      Slave_SQL_Running_State: Slave has read all relay log; waiting for more updates
           Master_Retry_Count: 86400
                  Master_Bind:
      Last_IO_Error_Timestamp:
     Last_SQL_Error_Timestamp:
               Master_SSL_Crl:
           Master_SSL_Crlpath:
           Retrieved_Gtid_Set:
            Executed_Gtid_Set:
                Auto_Position: 0
         Replicate_Rewrite_DB:
                 Channel_Name:
           Master_TLS_Version:
       Master_public_key_path:
        Get_master_public_key: 1
            Network_Namespace:
```

The table `t1` with some data for use in `MoveTables`, is already present in the external instances:

```
$ ./use_all_masters "use source; show create table t1\G"  
*************************** 1. row ***************************
       Table: t1
Create Table: CREATE TABLE `t1` (
  `c1` int(11) NOT NULL,
  PRIMARY KEY (`c1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci

$ ./use_all_slaves "use source; select * from t1;"
server: 1
c1
1
2
3
4
server: 2
c1
1
2
3
4
```

Tablet status and Replication positions for the external keyspace (`keyspace3`):
```
$ ~/vt/vitess/bin/vtctlclient -server 127.0.0.1:15999  ListAllTablets
zone1-0000000100 keyspace1 0 master 192.168.0.134:15100 192.168.0.134:17100 [] 2021-01-19T00:15:51Z
zone1-0000000101 keyspace1 0 replica 192.168.0.134:15101 192.168.0.134:17101 [] <null>
zone1-0000000102 keyspace1 0 rdonly 192.168.0.134:15102 192.168.0.134:17102 [] <null>
zone1-0000000300 keyspace3 0 master 192.168.0.134:15300 127.0.0.1:20617 [] 2021-01-19T00:15:52Z
zone1-0000000301 keyspace3 0 replica 192.168.0.134:15301 127.0.0.1:20618 [] <null>
zone1-0000000302 keyspace3 0 rdonly 192.168.0.134:15302 127.0.0.1:20619 [] <null>

$ ~/vt/vitess/bin/vtctlclient -server 127.0.0.1:15999  ShardReplicationPositions keyspace3/0
zone1-0000000300 keyspace3 0 master 192.168.0.134:15300 127.0.0.1:20617 [] 2021-01-19T00:15:52Z FilePos/mysql-bin.000001:328858 0
zone1-0000000301 keyspace3 0 replica 192.168.0.134:15301 127.0.0.1:20618 [] <null> FilePos/mysql-bin.000001:328858 0
zone1-0000000302 keyspace3 0 rdonly 192.168.0.134:15302 127.0.0.1:20619 [] <null> FilePos/mysql-bin.000001:328858 0
```

Now, we do a `MoveTables` for table `t1`:

```
$ ~/vt/vitess/bin/vtctlclient -server localhost:15999 MoveTables -workflow=keyspace3_2_keyspace1 keyspace3 keyspace1 '{"t1":{}}'
```

Check `MoveTables` workflow status:

```
$ ~/vt/vitess/bin/vtctlclient -server 127.0.0.1:15999  Workflow keyspace1.keyspace3_2_keyspace1 list
{
        "Workflow": "keyspace3_2_keyspace1",
        "SourceLocation": {
                "Keyspace": "keyspace3",
                "Shards": [
                        "0"
                ]
        },
        "TargetLocation": {
                "Keyspace": "keyspace1",
                "Shards": [
                        "0"
                ]
        },
        "MaxVReplicationLag": 1611015814,
        "ShardStatuses": {
                "0/zone1-0000000100": {
                        "MasterReplicationStatuses": [
                                {
                                        "Shard": "0",
                                        "Tablet": "zone1-0000000100",
                                        "ID": 2,
                                        "Bls": {
                                                "keyspace": "keyspace3",
                                                "shard": "0",
                                                "filter": {
                                                        "rules": [
                                                                {
                                                                        "match": "t1",
                                                                        "filter": "select * from t1"
                                                                }
                                                        ]
                                                }
                                        },
                                        "Pos": "FilePos/mysql-bin.000001:326452",
                                        "StopPos": "",
                                        "State": "Running",
                                        "MaxReplicationLag": 9223372036854775807,
                                        "DBName": "vt_keyspace1",
                                        "TransactionTimestamp": 0,
                                        "TimeUpdated": 1611015814,
                                        "Message": "",
                                        "CopyState": null
                                }
                        ],
                        "TabletControls": null,
                        "MasterIsServing": true
                }
        }
}
```

Access the target keyspace via vtgate, confirming that the rows have been copied:
```
$ mysql -u user -p -h 127.0.0.1 -P 15306 -A
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 5.7.25-Vitess  MySQL Community Server - GPL

Copyright (c) 2009-2020 Percona LLC and/or its affiliates
Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use keyspace1;
Database changed
mysql> select * from t1;
+----+
| c1 |
+----+
|  1 |
|  2 |
|  3 |
|  4 |
+----+
4 rows in set (0.01 sec)
```

Also note the `pos` in the Workflow list command;  the Vreplication stream is
from one of the replicas of the external keyspace (`keyspace3`), not from
the master (cf. the `ShardReplicationPositions` and `show master status`
output from earlier)

Now, we run `SwitchReads` and `SwitchWrites`.  Note that no traffic is flowing
to the external keyspace at this time, either via Vitess or directly.

```
$ ~/vt/vitess/bin/vtctlclient -server localhost:15999 SwitchReads -tablet_type=replica keyspace1.keyspace3_2_keyspace1
$ ~/vt/vitess/bin/vtctlclient -server localhost:15999 SwitchReads -tablet_type=rdonly keyspace1.keyspace3_2_keyspace1
```

i.e. `SwitchReads` succeed without issue.

Now run `SwitchWrites`:

```
$ ~/vt/vitess/bin/vtctlclient -server localhost:15999 SwitchWrites keyspace1.keyspace3_2_keyspace1
(hangs, and after 30 seconds...)
E0118 16:26:38.435713   40618 main.go:67] E0119 00:26:38.435144 traffic_switcher.go:508] waitForCatchup failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
SwitchWrites Error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
E0118 16:26:38.460206   40618 main.go:72] remote error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

Relevant messages from the target keyspace master tablet:

```
I0118 16:26:08.404773   39699 rpc_server.go:84] TabletManager.VReplicationExec(query:"select val from _vt.resharding_journal where id=4098448490216452955" )(on zone1-0000000300 from ): (*tabletmanagerdata.VReplicationExecResponse)(nil)
I0118 16:26:08.407392   39699 shard_sync.go:78] Change in shard record
I0118 16:26:08.408519   39699 tm_state.go:108] Refreshing from Topo
I0118 16:26:08.431167   39699 tm_state.go:285] Blacklisting tables t1
I0118 16:26:08.431255   39699 state_manager.go:212] Starting transition to MASTER Serving, timestamp: 2021-01-19 00:15:52.708406296 +0000 UTC
I0118 16:26:08.431296   39699 state_manager.go:674] State: exiting lameduck
I0118 16:26:08.431315   39699 rpc_server.go:84] TabletManager.RefreshState()(on zone1-0000000300 from ): (*tabletmanagerdata.RefreshStateResponse)(nil)
I0118 16:26:09.550981   39699 controller.go:196] trying to find a tablet eligible for vreplication. stream id: 1
I0118 16:26:09.554572   39699 tablet_picker.go:142] tablet picker found tablet alias:<cell:"zone1" uid:101 > hostname:"192.168.0.134" port_map:<key:"grpc" value:16101 > port_map:<key:"vt" value:15101 > keyspace:"keyspace1" shard:"0" type:REPLICA mysql_hostname:"192.168.0.134" mysql_port:17101
I0118 16:26:09.555107   39699 controller.go:208] found a tablet eligible for vreplication. stream id: 1  tablet: cell:"zone1" uid:101
E0118 16:26:09.580310   39699 vreplicator.go:125] Replicate error: error reading VReplication settings: checkpoint information not available in db for 1
E0118 16:26:09.580974   39699 controller.go:154] stream 1: error reading VReplication settings: checkpoint information not available in db for 1, retrying after 5s
I0118 16:26:14.582926   39699 controller.go:196] trying to find a tablet eligible for vreplication. stream id: 1
I0118 16:26:14.586153   39699 tablet_picker.go:142] tablet picker found tablet alias:<cell:"zone1" uid:101 > hostname:"192.168.0.134" port_map:<key:"grpc" value:16101 > port_map:<key:"vt" value:15101 > keyspace:"keyspace1" shard:"0" type:REPLICA mysql_hostname:"192.168.0.134" mysql_port:17101
I0118 16:26:14.586615   39699 controller.go:208] found a tablet eligible for vreplication. stream id: 1  tablet: cell:"zone1" uid:101
E0118 16:26:14.610883   39699 vreplicator.go:125] Replicate error: error reading VReplication settings: checkpoint information not available in db for 1
E0118 16:26:14.611596   39699 controller.go:154] stream 1: error reading VReplication settings: checkpoint information not available in db for 1, retrying after 5s
I0118 16:26:19.613538   39699 controller.go:196] trying to find a tablet eligible for vreplication. stream id: 1
I0118 16:26:19.617353   39699 tablet_picker.go:142] tablet picker found tablet alias:<cell:"zone1" uid:101 > hostname:"192.168.0.134" port_map:<key:"grpc" value:16101 > port_map:<key:"vt" value:15101 > keyspace:"keyspace1" shard:"0" type:REPLICA mysql_hostname:"192.168.0.134" mysql_port:17101
I0118 16:26:19.618078   39699 controller.go:208] found a tablet eligible for vreplication. stream id: 1  tablet: cell:"zone1" uid:101
E0118 16:26:19.643397   39699 vreplicator.go:125] Replicate error: error reading VReplication settings: checkpoint information not available in db for 1
E0118 16:26:19.643965   39699 controller.go:154] stream 1: error reading VReplication settings: checkpoint information not available in db for 1, retrying after 5s
I0118 16:26:24.645945   39699 controller.go:196] trying to find a tablet eligible for vreplication. stream id: 1
I0118 16:26:24.649678   39699 tablet_picker.go:142] tablet picker found tablet alias:<cell:"zone1" uid:101 > hostname:"192.168.0.134" port_map:<key:"grpc" value:16101 > port_map:<key:"vt" value:15101 > keyspace:"keyspace1" shard:"0" type:REPLICA mysql_hostname:"192.168.0.134" mysql_port:17101
I0118 16:26:24.650346   39699 controller.go:208] found a tablet eligible for vreplication. stream id: 1  tablet: cell:"zone1" uid:101
E0118 16:26:24.675811   39699 vreplicator.go:125] Replicate error: error reading VReplication settings: checkpoint information not available in db for 1
E0118 16:26:24.676725   39699 controller.go:154] stream 1: error reading VReplication settings: checkpoint information not available in db for 1, retrying after 5s
```

From the master vttablet in the source keyspace:

```
E0118 16:26:38.435320   39594 engine.go:690] Error waiting for pos: FilePos/mysql-bin.000001:328858, last pos: FilePos/mysql-bin.000001:326452: context canceled, wait time: 29.99771909s
W0118 16:26:38.435643   39594 rpc_server.go:80] TabletManager.VReplicationWaitForPos(id:2 position:"FilePos/mysql-bin.000001:328858" )(on zone1-0000000100 from ) error: error waiting for pos: FilePos/mysql-bin.000001:328858, last pos: FilePos/mysql-bin.000001:326452: context canceled, wait time: 29.997985656s
```

So, the `SwitchWrites` is waiting for `mysql-bin.000001:328858`; but if we
(again) look at the binary logs served by the source keyspace replicas, we see
that any client will wait forever for these, since the file:pos is different and we're only at position 326452:

```
$ ./use_all_slaves "show master status\G"
server: 1
*************************** 1. row ***************************
             File: mysql-bin.000001
         Position: 326452
     Binlog_Do_DB:
 Binlog_Ignore_DB:
Executed_Gtid_Set:
server: 2
*************************** 1. row ***************************
             File: mysql-bin.000001
         Position: 326452
     Binlog_Do_DB:
 Binlog_Ignore_DB:
Executed_Gtid_Set:
```

A cursory reading of the traffic_switcher:waitForCatchup(..) code shows that indeed we are not doing anything to translate the master filepos position to a corresponding position on the replica;  and the code will only work when the vreplication is running from a replica iff GTID replication is used.

The workaround is to use `-tablet_types master` for the `MoveTables` operation;  which may not be possible in a production migration scenario.

**Comment by hihihuhu** [comment] 2021-01-19 21:16
We are seeing significant write performance drop when there are many binlog consumers connecting to Aurora, so in order to walk around this limit of Aurora, we create a standalone Aurora cluster replicates from the production Aurora cluster, use the new Aurora as read only tablet in Vitess and connect VReplications to it. Thus it could be important to have MoveTables works from replica without GTiD enabled for our use cases.

We are thinking, to add a new flag `test_catch_up_on_source` in `SwitchWrites` with default value false, and when it is true, the wait for catchup process will be

1. get the source tablet UID of the VReplication
2. wait the source tablet to reach the position of the master by using `WaitForPosition`
3. get the current position of source tablet by using `MasterPosition`
4. wait for the VReplication to reach the position of source tablet by using `VReplicationWaitForPos`

For step 1, a new api to get source tablet UID of a VReplication in VTTablet is needed.

Do you think this could be a feasible fix? Thanks!

**Comment by mattlord** [comment] 2024-09-25 16:23
I'm going to close this as expected behavior. 

I say that because file/position is specific to an instance of MySQL. This means that 1) you cannot have any failovers within a shard during the process 2) you have to use a stable set of tablets, so e.g. using --tablet-types=PRIMARY. 

You simply cannot use file/position when the tablets/mysqld instances used changes.

**Closed by mattlord** 2024-09-25 16:23 UTC
Labels: Type: Bug, Component: VReplication
