### ISSUE TITLE
Bug Report: 404 page not found

### ISSUE THREAD

**Issue by javamyth** [vitessio/vitess#15593] opened 2024-03-29 07:38 UTC
### Overview of the Issue

Hello, I set up the service locally, executed 101_initial_cluster.sh and visited the vtadmin-web page. On the right side of the vtctlds menu, I clicked localhost:15999, jumped to localhost:15000, and then reported 404 page not found. .Is there something wrong here?
![0328](https://github.com/vitessio/vitess/assets/49809173/85483689-a934-4812-a90f-b68ba6b42097)
![0328002](https://github.com/vitessio/vitess/assets/49809173/d8da9292-b581-4720-8746-f56677e17f14)

### Reproduction Steps

git checkout main && make build

pushd examples/local

./101_initial_cluster.sh

### Binary Version

```sh
vtgate version Version: 18.0.0 (Git revision built on Tue Mar 26 10:16:20 CST 2024 by using go1.21.4 darwin/arm64
```

### Operating System and Environment details

```sh
N/A
```

**Comment by shlomi-noach** [comment] 2024-03-31 07:27
Does this report discuss a new issue? It looks like a duplicate of  https://github.com/vitessio/vitess/issues/15587. Please clarify, or kindly close the issue 🙏

**Closed** 2024-04-09 03:37 UTC
Labels: Type: Bug, Type: Documentation, Component: Documentation
