### ISSUE TITLE
Bug Report: VStream with StopOnReshard when resumed does not retransmit Journal event

### ISSUE THREAD

**Issue by twthorn** [vitessio/vitess#16621] opened 2024-08-20 19:13 UTC
### Overview of the Issue

For a VStream with StopOnReshard flag enabled the Journal event is sent correctly if the vstream is active when the reshard happens. However, if, after the reshard is complete, the vstream is restarted from the previous shard/gtid, it will not receive the Journal event.

### Reproduction Steps

Modify vstream_client.go

```diff
--- a/examples/local/vstream_client.go
+++ b/examples/local/vstream_client.go
@@ -42,17 +42,26 @@ func main() {
        var vgtid *binlogdatapb.VGtid
        if streamCustomer {
                vgtid = &binlogdatapb.VGtid{
-                       ShardGtids: []*binlogdatapb.ShardGtid{{
-                               Keyspace: "customer",
-                               Shard:    "-80",
-                               // Gtid "" is to stream from the start, "current" is to stream from the current gtid
-                               // you can also specify a gtid to start with.
-                               Gtid: "", //"current"  // "MySQL56/36a89abd-978f-11eb-b312-04ed332e05c2:1-265"
-                       }, {
-                               Keyspace: "customer",
-                               Shard:    "80-",
-                               Gtid:     "",
-                       }}}
+                         ShardGtids: []*binlogdatapb.ShardGtid{
+                                       {
+                                               Keyspace: "customer",
+                                               Shard:    "0",
+                                               Gtid: "",
+                                       },
+                               },
+                       }
        } else {
                vgtid = &binlogdatapb.VGtid{
                        ShardGtids: []*binlogdatapb.ShardGtid{{
@@ -75,6 +84,8 @@ func main() {
        flags := &vtgatepb.VStreamFlags{
                //MinimizeSkew:      false,
                //HeartbeatInterval: 60, //seconds
+              StopOnReshard: true,
        }

```

```
./101_initial_cluster.sh; mysql < ../common/insert_commerce_data.sql; ./201_customer_tablets.sh ; ./202_move_tables.sh; ./203_switch_reads.sh; ./204_switch_writes.sh; ./205_clean_commerce.sh;
```

```
go run vstream_client.go
```

Run the reshard
```
./301_customer_sharded.sh; ./302_new_shards.sh; ./303_reshard.sh; ./304_switch_reads.sh; ./305_switch_writes.sh;
```

Receive the Journal event

```
[type:BEGIN timestamp:1724172966 current_time:1724172966973269000 keyspace:"customer" shard:"0" type:JOURNAL timestamp:1724172966 journal:{id:8200191490597391617 migration_type:SHARDS tables:"/.*" local_position:"MySQL56/52f690c6-5f14-11ef-8999-f4f6f6eab5c9:1-365" shard_gtids:{keyspace:"customer" shard:"-80" gtid:"MySQL56/f526d4b4-5f14-11ef-8d83-4127049b0131:1-154"} shard_gtids:{keyspace:"customer" shard:"80-" gtid:"MySQL56/f9de4c3a-5f14-11ef-b8ff-f0e7b3cce20a:1-154"} participants:{keyspace:"customer" shard:"0"}} current_time:1724172966973826000 keyspace:"customer" shard:"0"]
stream ended
```

Restart the stream from previous local_position

```diff
+++ b/examples/local/vstream_client.go
@@ -42,17 +42,26 @@ func main() {
        var vgtid *binlogdatapb.VGtid
        if streamCustomer {
                vgtid = &binlogdatapb.VGtid{
-                       ShardGtids: []*binlogdatapb.ShardGtid{{
-                               Keyspace: "customer",
-                               Shard:    "-80",
-                               // Gtid "" is to stream from the start, "current" is to stream from the current gtid
-                               // you can also specify a gtid to start with.
-                               Gtid: "", //"current"  // "MySQL56/36a89abd-978f-11eb-b312-04ed332e05c2:1-265"
-                       }, {
-                               Keyspace: "customer",
-                               Shard:    "80-",
-                               Gtid:     "",
-                       }}}
+                         ShardGtids: []*binlogdatapb.ShardGtid{
+                                       {
+                                               Keyspace: "customer",
+                                               Shard:    "0",
+                                               Gtid: "MySQL56/52f690c6-5f14-11ef-8999-f4f6f6eab5c9:1-365",
+                                       },
+                               },
+                       }
```

Stream doesn't receive journal event
```
[type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/52f690c6-5f14-11ef-8999-f4f6f6eab5c9:1-372"}} keyspace:"customer" shard:"0" type:OTHER timestamp:1724172966 current_time:1724173661848590000 keyspace:"customer" shard:"0"]
stream ended
```

### Binary Version

```sh
Used main branch at commit 0af3d38
```

### Operating System and Environment details

```sh
On Mac OS locally
```

### Log Fragments

```sh
See reproduction steps
```

**Comment by mattlord** [comment] 2024-08-22 19:06
Thanks, @twthorn ! I believe the problem here is that when resuming we are picking up from a position as per usual and the reshard event is not injected into the stream because the reshard action doesn't occur in this scenario. So we'd need to be sure to include the journal event in the stream, at least when `StopOnReshard` is set, but we should probably do that regardless of the setting.

**Comment by mattlord** [comment] 2024-08-22 19:55
@twthorn I've done some testing and verified that we do indeed send the reshard journal event as expected in this scenario.

The reason you don't see it in your specific test, I believe, is because the reshard journal event was *already* sent in the GTID position noted in the reshard journal event for the old shard, and thus when you resumed from the old position we did not *resend* the journal event, instead the stream ends because that's the last position in the stream on the old shard. I think that this is an oddity of `StopOnReshard`, being followed by a resume where you do NOT specify the new shards that you got previously in the steam which were included in that event's position. I'm not sure we can or should try and work around this as it seems like a user error to me as we would not want to re-stream an event for a position we've already streamed (going back and including events that occurred before the provided position).

I'm going to close this as not a bug for now, but please let me know if I'm missing something.

**Comment by twthorn** [comment] 2024-08-22 20:26
Based on discussion, the issue with the above example is that it uses the `local_position` GTID which is the GTID of the journal event and that's why no journal event is re-sent. Here's another example using an earlier offset to try to get the journal event to be resent.

All steps are the same for set up. The output of the first vstream_client.go run is
```
tthornton at tthornt-ltm9dwz in ~/git/twthorn/vitess/examples/local on main [!?$]
$ go run vstream_client.go                                                                                                                                                                                                                         [type:BEGIN keyspace:"customer" shard:"0" type:FIELD field_event:{table_name:"customer.customer" fields:{name:"customer_id" type:INT64 table:"customer" org_table:"customer" database:"vt_customer" org_name:"customer_id" column_length:20 charset
:63 flags:49667 column_type:"bigint"} fields:{name:"email" type:VARBINARY table:"customer" org_table:"customer" database:"vt_customer" org_name:"email" column_length:128 charset:63 flags:128 column_type:"varbinary(128)"} keyspace:"customer" shard:"0" enum_set_string_values:true} keyspace:"customer" shard:"0"]
[type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-55"}} keyspace:"customer" shard:"0"]                                                                                            [type:ROW row_event:{table_name:"customer.customer" row_changes:{after:{lengths:1 lengths:16 values:"1alice@domain.com"}} keyspace:"customer" shard:"0"} keyspace:"customer" shard:"0" type:ROW row_event:{table_name:"customer.customer" row_chang
es:{after:{lengths:1 lengths:14 values:"2bob@domain.com"}} keyspace:"customer" shard:"0"} keyspace:"customer" shard:"0" type:ROW row_event:{table_name:"customer.customer" row_changes:{after:{lengths:1 lengths:18 values:"3charlie@domain.com"}} keyspace:"customer" shard:"0"} keyspace:"customer" shard:"0" type:ROW row_event:{table_name:"customer.customer" row_changes:{after:{lengths:1 lengths:14 values:"4dan@domain.com"}} keyspace:"customer" shard:"0"} keyspace:"customer" shard:"0" ty
pe:ROW row_event:{table_name:"customer.customer" row_changes:{after:{lengths:1 lengths:14 values:"5eve@domain.com"}} keyspace:"customer" shard:"0"} keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-55" table_p_ks:{table_name:"customer" lastpk:{fields:{name:"customer_id" type:INT64 charset:63 flags:49667} rows:{lengths:1 values:"5"}}}}} keyspace:"customer" shard:"0" type:COMMIT keyspace:"cu
stomer" shard:"0"]
[type:BEGIN keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-55"}} keyspace:"customer" shard:"0" type:COMMIT keyspace:"customer" shard:"0"]
[type:COPY_COMPLETED keyspace:"customer" shard:"0" type:COPY_COMPLETED]
[type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-56"}} keyspace:"customer" shard:"0" type:DDL timestamp:1724357681 statement:"alter table customer change customer_id customer_id
 bigint not null" current_time:1724357681477144000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724357681 current_time:1724357681477159000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-57"}} keyspace:"customer" shard:"
0" type:COMMIT timestamp:1724357681 current_time:1724357681477191000 keyspace:"customer" shard:"0"]
[type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-58"}} keyspace:"customer" shard:"0" type:OTHER timestamp:1724357681 current_time:1724357681487039000 keyspace:"customer" shard:"
0"]                                                                                                                                                                                                                                                [type:BEGIN timestamp:1724357681 current_time:1724357681487058000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-59"}} keyspace:"customer" shard:"
0" type:COMMIT timestamp:1724357681 current_time:1724357681487084000 keyspace:"customer" shard:"0"]                                                                                                                                                [type:BEGIN timestamp:1724357681 current_time:1724357681491607000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-60"}} keyspace:"customer" shard:"
0" type:COMMIT timestamp:1724357681 current_time:1724357681491628000 keyspace:"customer" shard:"0"]                                                                                                                                                [type:BEGIN timestamp:1724357708 current_time:1724357708694767000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-61"}} keyspace:"customer" shard:"
0" type:COMMIT timestamp:1724357708 current_time:1724357708694776000 keyspace:"customer" shard:"0"]                                                                                                                                                [type:BEGIN timestamp:1724357708 current_time:1724357708695785000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-62"}} keyspace:"customer" shard:"
0" type:COMMIT timestamp:1724357708 current_time:1724357708695798000 keyspace:"customer" shard:"0"]                                                                                                                                                [type:BEGIN timestamp:1724357708 current_time:1724357708696764000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-63"}} keyspace:"customer" shard:"
0" type:COMMIT timestamp:1724357708 current_time:1724357708696773000 keyspace:"customer" shard:"0"]                                                                                                                                                [type:BEGIN timestamp:1724357708 current_time:1724357708697667000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-64"}} keyspace:"customer" shard:"
0" type:COMMIT timestamp:1724357708 current_time:1724357708697674000 keyspace:"customer" shard:"0"]                                                                                                                                                [type:BEGIN timestamp:1724357708 current_time:1724357708699052000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-65"}} keyspace:"customer" shard:"
0" type:COMMIT timestamp:1724357708 current_time:1724357708699072000 keyspace:"customer" shard:"0"]                                                                                                                                                [type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-66"}} keyspace:"customer" shard:"0" type:OTHER timestamp:1724357708 current_time:1724357708701332000 keyspace:"customer" shard:"
0"]                                                                                                                                                                                                                                                [type:BEGIN timestamp:1724357708 current_time:1724357708703815000 keyspace:"customer" shard:"0" type:JOURNAL timestamp:1724357708 journal:{id:8200191490597391617 migration_type:SHARDS tables:"/.*" local_position:"MySQL56/f4867442-60c2-11ef-89a
2-aad21e1f40e4:1-60" shard_gtids:{keyspace:"customer" shard:"80-" gtid:"MySQL56/329851c4-60c3-11ef-9f73-9d9b31231c25:1-48"} shard_gtids:{keyspace:"customer" shard:"-80" gtid:"MySQL56/2c926864-60c3-11ef-9e19-e4baf6a453af:1-52"} participants:{keyspace:"customer" shard:"0"}} current_time:1724357708704326000 keyspace:"customer" shard:"0"]
stream ended
```

Note local position is `MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-60` so we want to be earlier than that

Then with this we update our gtid to be this one, which uses an earlier VGTID sent in the above output

```diff
+                         ShardGtids: []*binlogdatapb.ShardGtid{
+                                       {
+                                               Keyspace: "customer",
+                                               Shard:    "0",
+                                               Gtid: "MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-55",
+                                       },
+                               },
+                       }
```

Then the output is
```
tthornton at tthornt-ltm9dwz in ~/git/twthorn/vitess/examples/local on main [!?$]
$ go run vstream_client.go
[type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-56"}} keyspace:"customer" shard:"0" type:DDL timestamp:1724357681 statement:"alter table customer change customer_id customer_id bigint not null" current_time:1724358223678138000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724357681 current_time:1724358223678150000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-57"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724357681 current_time:1724358223678212000 keyspace:"customer" shard:"0"]
[type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-58"}} keyspace:"customer" shard:"0" type:OTHER timestamp:1724357681 current_time:1724358223678254000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724357681 current_time:1724358223678262000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-59"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724357681 current_time:1724358223678275000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724357681 current_time:1724358223678281000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-60"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724357681 current_time:1724358223678294000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724357708 current_time:1724358223678297000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-61"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724357708 current_time:1724358223678301000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724357708 current_time:1724358223678304000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-62"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724357708 current_time:1724358223678309000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724357708 current_time:1724358223678317000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-63"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724357708 current_time:1724358223678325000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724357708 current_time:1724358223678337000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-64"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724357708 current_time:1724358223678356000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724357708 current_time:1724358223678387000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-65"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724357708 current_time:1724358223678401000 keyspace:"customer" shard:"0"]
[type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/f4867442-60c2-11ef-89a2-aad21e1f40e4:1-66"}} keyspace:"customer" shard:"0" type:OTHER timestamp:1724357708 current_time:1724358223678409000 keyspace:"customer" shard:"0"]
stream ended
```

There is no Journal event sent on for the second run of vstream_client from an offset before the Journal event's local_position.

**Comment by mattlord** [comment] 2024-08-22 20:37
I'm going to reopen. I've also confirmed this.

Results from the stream as the new shards were being setup to the point the SwitchTraffic was done:
```
[type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-56"}} keyspace:"customer" shard:"0" type:DDL timestamp:1724358813 statement:"alter table customer change customer_id customer_id bigint not null" current_time:1724358813317200000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358813 current_time:1724358813317217000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-57"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358813 current_time:1724358813317235000 keyspace:"customer" shard:"0"]
[type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-58"}} keyspace:"customer" shard:"0" type:OTHER timestamp:1724358813 current_time:1724358813327451000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358813 current_time:1724358813327465000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-59"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358813 current_time:1724358813327481000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358813 current_time:1724358813334446000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-60"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358813 current_time:1724358813334465000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358838 current_time:1724358838278825000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-61"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358838 current_time:1724358838278838000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358838 current_time:1724358838279486000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-62"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358838 current_time:1724358838279493000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358838 current_time:1724358838280109000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-63"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358838 current_time:1724358838280116000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358838 current_time:1724358838280896000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-64"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358838 current_time:1724358838280902000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358838 current_time:1724358838282820000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-65"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358838 current_time:1724358838282827000 keyspace:"customer" shard:"0"]
[type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-66"}} keyspace:"customer" shard:"0" type:OTHER timestamp:1724358838 current_time:1724358838283299000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358838 current_time:1724358838285709000 keyspace:"customer" shard:"0" type:JOURNAL timestamp:1724358838 journal:{id:8200191490597391617 migration_type:SHARDS tables:"/.*" local_position:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-60" shard_gtids:{keyspace:"customer" shard:"-80" gtid:"MySQL56/cceb6e8a-60c5-11ef-a76e-47447da7cf19:1-52"} shard_gtids:{keyspace:"customer" shard:"80-" gtid:"MySQL56/d57ed38e-60c5-11ef-8d43-4d5be053fe00:1-52"} participants:{keyspace:"customer" shard:"0"}} current_time:1724358838286255000 keyspace:"customer" shard:"0"]
stream ended
```

If I start a stream from that first position:
❯ go run vstream_client.go
[type:BEGIN timestamp:1724358813 current_time:1724358892353214000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-57"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358813 current_time:1724358892353229000 keyspace:"customer" shard:"0"]
[type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-58"}} keyspace:"customer" shard:"0" type:OTHER timestamp:1724358813 current_time:1724358892357207000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358813 current_time:1724358892357215000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-59"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358813 current_time:1724358892357242000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358813 current_time:1724358892357249000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-60"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358813 current_time:1724358892357262000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358838 current_time:1724358892357266000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-61"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358838 current_time:1724358892357281000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358838 current_time:1724358892357294000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-62"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358838 current_time:1724358892357301000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358838 current_time:1724358892357308000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-63"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358838 current_time:1724358892357314000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358838 current_time:1724358892357323000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-64"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358838 current_time:1724358892357332000 keyspace:"customer" shard:"0"]
[type:BEGIN timestamp:1724358838 current_time:1724358892357340000 keyspace:"customer" shard:"0" type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-65"}} keyspace:"customer" shard:"0" type:COMMIT timestamp:1724358838 current_time:1724358892357343000 keyspace:"customer" shard:"0"]
[type:VGTID vgtid:{shard_gtids:{keyspace:"customer" shard:"0" gtid:"MySQL56/9ada956a-60c5-11ef-937a-2ddbc33ff0f8:1-66"}} keyspace:"customer" shard:"0" type:OTHER timestamp:1724358838 current_time:1724358892357346000 keyspace:"customer" shard:"0"]
stream ended
```

We don't get the reshard journal event which tells us where to start streaming from.

**Closed** 2024-08-29 02:33 UTC
Labels: Type: Bug, Component: VReplication
