### ISSUE TITLE
panic: binlog_streamer.go:181] stream ended

### ISSUE THREAD

**Issue by acharis** [vitessio/vitess#4801] opened 2019-04-10 17:09 UTC
#### Overview of the Issue

When starting up a tablet with SHA ae7b400 we see the following:

```
I0410 01:15:26.662889       8 binlog_streamer.go:181] stream ended @ <nil>, err = <nil>
panic: runtime error: slice bounds out of range

goroutine 515 [running]:
vitess.io/vitess/go/mysql.printJSONString(0xc001546c3b, 0xb6, 0x1bb, 0x0, 0xc00104bc70)
vitess-build/src/vitess.io/vitess/go/mysql/binlog_event_json.go:353 +0x17e
vitess.io/vitess/go/mysql.printJSONValue(0x94110c, 0xc001546c3b, 0xb6, 0x1bb, 0x12c5800, 0xc00104bc70, 0x0, 0x0)
vitess-build/src/vitess.io/vitess/go/mysql/binlog_event_json.go:98 +0x562
vitess.io/vitess/go/mysql.printJSONValueEntry(0xc001546ae9, 0x208, 0x30d, 0x57, 0x12c5800, 0xc00104bc70, 0x0, 0x0)
vitess-build/src/vitess.io/vitess/go/mysql/binlog_event_json.go:215 +0x2dc
vitess.io/vitess/go/mysql.printJSONObject(0xc001546ae9, 0x208, 0x30d, 0xc000e8ca00, 0xc00104bc70, 0x40e1c8, 0x70)
vitess-build/src/vitess.io/vitess/go/mysql/binlog_event_json.go:139 +0x430
vitess.io/vitess/go/mysql.printJSONValue(0x1071500, 0xc001546ae9, 0x208, 0x30d, 0x1, 0xc00104bc70, 0x1, 0x117625c)
vitess-build/src/vitess.io/vitess/go/mysql/binlog_event_json.go:74 +0x126
vitess.io/vitess/go/mysql.printJSONData(0xc001546ae8, 0x209, 0x30e, 0x0, 0xa, 0xc0010476b0, 0x1, 0x8)
vitess-build/src/vitess.io/vitess/go/mysql/binlog_event_json.go:65 +0x93
vitess.io/vitess/go/mysql.CellValue(0xc001546aa5, 0x34d, 0x351, 0x3f, 0x81e000400f5, 0x1, 0xc0010476b0, 0x1, 0x8, 0x1, ...)
vitess-build/src/vitess.io/vitess/go/mysql/binlog_event_rbr.go:811 +0xb3d
vitess.io/vitess/go/vt/binlog.writeValuesAsSQL(0xc0015cacc0, 0xc000d97c80, 0xc000e8d9a0, 0x0, 0x0, 0x1, 0xc0012489d0, 0xd, 0x113, 0xc00010814d, ...)
vitess-build/src/vitess.io/vitess/go/vt/binlog/binlog_streamer.go:752 +0x598
vitess.io/vitess/go/vt/binlog.(*Streamer).appendInserts(0xc000dbd860, 0xc001d1c000, 0x1, 0xa, 0xc000d97c80, 0xc000e8d9a0, 0x26, 0x2b, 0xc000dcdc00)
vitess-build/src/vitess.io/vitess/go/vt/binlog/binlog_streamer.go:610 +0x1f8
vitess.io/vitess/go/vt/binlog.(*Streamer).parseEvents(0xc000dbd860, 0x12d9300, 0xc000d7c140, 0xc00024f500, 0xc000e240c0, 0xc00024f500, 0x0, 0x0)
vitess-build/src/vitess.io/vitess/go/vt/binlog/binlog_streamer.go:534 +0x19b0
vitess.io/vitess/go/vt/binlog.(*Streamer).Stream(0xc000dbd860, 0x12d9300, 0xc000d7c140, 0x0, 0x0)
vitess-build/src/vitess.io/vitess/go/vt/binlog/binlog_streamer.go:233 +0x201
vitess.io/vitess/go/vt/vttablet/tabletserver.(*ReplicationWatcher).Process(0xc0002367c0, 0x12d9300, 0xc000d7c140, 0x1d5e800)
vitess-build/src/vitess.io/vitess/go/vt/vttablet/tabletserver/replication_watcher.go:138 +0x1ac
created by vitess.io/vitess/go/vt/vttablet/tabletserver.(*ReplicationWatcher).Open
vitess-build/src/vitess.io/vitess/go/vt/vttablet/tabletserver/replication_watcher.go:97 +0xcd
```

I'll post a schema + sample data when I've got a clear and minimal reproduction.

**Comment by makmanalp** [comment] 2019-07-19 00:10
update: https://hubspot.slack.com/archives/G370Q92RL/p1563322762419300

and 

https://git.hubteam.com/gist/makmanalp/a7908b94698ee05a03c04759d77e0fca

**Comment by deepthi** [comment] 2019-07-19 01:45
@makmanalp those URLs don't for non-hubspot users obviously. Do you want to post the actual content to this issue?

**Comment by makmanalp** [comment] 2019-07-19 20:33
@deepthi Er, I'm so sorry, I thought for a moment that this was our internal github :-( I'm working on it actively and have a reproducer, I'm now testing whether we see it on a more recent git version or not.

**Comment by makmanalp** [comment] 2019-07-19 20:33
I'll update with more details today when I get somewhere useful

**Comment by makmanalp** [comment] 2019-07-22 23:30
OK, I have a minimal reproducer:

```sql
-- schema
CREATE TABLE `binlog_crash` (
  `id` int NOT NULL PRIMARY KEY,
  `test` json NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8;


-- Won't crash replica vttablets
insert into binlog_crash(id, test) values
(
1,
'"SUGUSUGUSUGUSUGUSUGUSUGSUGUSUGUSUGUSUGUSUGUSUGUSUGUSUGSUGUSUGUSUGUSUGUSUGUSUGUSUGUSUGUSUGSUGUSUGUSUGUSUGUSUGUSUGUSUGUSUGSUGUSUGUS"'
)

-- Will crash replica vttablets
insert into binlog_crash(id, test) values
(
2,
'"SUGUSUGUSUGUSUGUSUGUSUGSUGUSUGUSUGUSUGUSUGUSUGUSUGUSUGSUGUSUGUSUGUSUGUSUGUSUGUSUGUSUGUSUGSUGUSUGUSUGUSUGUSUGUSUGUSUGUSUGSUGUSUGUSU"'
)
```

The gist is that 129 characters worth of Sugu's in a JSON column will not crash, but 130 will. Our example was deeper within a much larger json object, and the size of the rest of the object didn't seem to matter.

130 seems a very round number, probably something like a manually allocated fixed-size buffer in a parser somewhere for 128 characters plus 2 quote characters. Could also be 512 / 520 since it's 4 bytes per character in that charset (utf8mb4).

**Comment by deepthi** [comment] 2019-07-22 23:46
there's a unit test that is supposed to cover this case with a string length of 130:
https://github.com/vitessio/vitess/blob/master/go/mysql/binlog_event_json_test.go#L52

so I'll be curious to know where the bug is once you find it.

**Comment by makmanalp** [comment] 2019-07-22 23:54
Looks like that got committed Mar 5th, merged on Mar 12, our SHA is from Mar 27. Trying to reproduce with a much more recent tablet sha but running into unrelated problems, will keep you posted tomorrow.

**Comment by acharis** [comment] 2019-07-23 14:45
Mali was able to repro against 40818a5

**Closed** 2019-07-30 05:13 UTC
