### ISSUE TITLE
vttablet: query regression for json extract operator ->

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#9951] opened 2022-03-22 22:17 UTC
v12.0 correctly handled queries using `->` and `->>`, however v13 throws a syntax error. Note that it is a vttablet error, not a vtgate syntax error

https://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#operator_json-column-path

```
select data ->> '$.kindId'
     from iam__hubspot_workspace_user_syncer__msgs
     where attributes ->> '$.latestError' = 'user not found'
[2022-03-22 16:07:40] [HY000][1105] target: iam.0.primary: vttablet: rpc error: code = InvalidArgument desc = syntax error at position 24 near ':vtg1' (CallerID: nozzleadmin)
```

**Comment by GuptaManan100** [comment] 2022-04-04 04:06
Thankyou for reporting this issue @derekperkins. The fix for it is ready at https://github.com/vitessio/vitess/pull/10015. I will also backport this to release-13 when it is merged and we will do a minor release as well, since this issue causes regression in queries which worked previously

**Comment by GuptaManan100** [comment] 2022-04-04 06:34
Backport PR is ready at https://github.com/vitessio/vitess/pull/10022

**Closed** 2022-04-04 09:37 UTC
Labels: Type: Bug, Component: Query Serving, Type: Regression
