### ISSUE TITLE
Binlog backup

### ISSUE THREAD

**Issue by bbeaudreault** [vitessio/vitess#2796] opened 2017-04-22 03:44 UTC
Vitess currently has built in workflows for backups and restoring from backups. What's missing is a separate workflow for backing up binlogs, likely at a more frequent rate than full backups. Restoring from binlogs can be used for disaster recovery (lost master and slaves), as well as cases where you need to repair the database in the face of bad/corrupt writes.

It would be great if at least the first part of that was covered or at least facilitated by vitess.

**Comment by makmanalp** [comment] 2019-06-04 21:31
Dupe of #3581

**Comment by derekperkins** [comment] 2020-06-09 22:48
Even though this was created first, the conversation is all on the other issue. Whoever created it really should have done a better search, but you can't filter out all the idiots. :)

**Closed by derekperkins** 2020-06-09 22:48 UTC
Labels: Component: Backup, P3, Type: Feature Request
