### ISSUE TITLE
101 & 203 kubernetes helm install has problems

### ISSUE THREAD

**Issue by tx19980520** [vitessio/vitess#5606] opened 2019-12-20 07:02 UTC
#### Overview of the Issue

running vitess tutorial on k3s use kubernetes tutorial

#### Reproduction Steps

I just running helm on k3s and I have meet  two different performance.(I have changed apiVersion to apps/v1)
First:
`helm install ../../helm/vitess/ -g -f 101_initial_cluster.yaml` may be failed about job `commerce-apply-schema-initial`
```shell
NAME                                 COMPLETIONS   DURATION   AGE
commerce-apply-vschema-initial       1/1           54s        6m31s
commerce-apply-schema-initial        0/1           6m31s      6m31s
zone1-commerce-0-init-shard-master   1/1           74s        6m31s
```
Second: 
when I run ``
`helm upgrade $release ../../helm/vitess/ -f 203_vertical_split.yaml`. vtworker-vertical-split job does not work.
Since The document  say it may be failed and I can restart the job.  I think the job can set always restart, and I can't debug. 
```bash
ubuntu@server:~/vitess/examples/helm$ kubectl describe job vtworker-vertical-split
Name:           vtworker-vertical-split
Namespace:      default
Selector:       controller-uid=17cb3100-2dc6-40af-9d2a-54b02340c8af
Labels:         app=vitess
                component=vtworker
                controller-uid=17cb3100-2dc6-40af-9d2a-54b02340c8af
                job-name=vtworker-vertical-split
                vtworkerJob=true
Annotations:    <none>
Parallelism:    1
Completions:    1
Start Time:     Fri, 20 Dec 2019 06:44:50 +0000
Pods Statuses:  0 Running / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app=vitess
           component=vtworker
           controller-uid=17cb3100-2dc6-40af-9d2a-54b02340c8af
           job-name=vtworker-vertical-split
           vtworkerJob=true
  Containers:
   vtjob:
    Image:      vitess/vtworker:helm-1.0.7-5
    Port:       <none>
    Host Port:  <none>
    Command:
      bash
    Args:
      -c
      set -ex
      
      eval exec /vt/bin/vtworker $(cat <<END_OF_COMMAND
        -topo_implementation="etcd2"
        -topo_global_server_address="etcd-global-client.default:2379"
        -topo_global_root=/vitess/global
        -cell="zone1"
        -logtostderr=true
        -stderrthreshold=0
      END_OF_COMMAND
      ) VerticalSplitClone -min_rdonly_tablets=1 -tables=customer,corder customer/0
      
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type     Reason                Age                From            Message
  ----     ------                ----               ----            -------
  Normal   SuccessfulCreate      15m                job-controller  Created pod: vtworker-vertical-split-z4vq7
  Normal   SuccessfulDelete      15m                job-controller  Deleted pod: vtworker-vertical-split-z4vq7
  Warning  BackoffLimitExceeded  15m (x2 over 15m)  job-controller  Job has reached the specified backoff limit

```
#### Binary version

```sh
ubuntu@server:~/vitess/examples/helm$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3-k3s.2", GitCommit:"e7e6a3c4e9a7d80b87793612730d10a863a25980", GitTreeState:"clean", BuildDate:"2019-11-18T18:31:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
ubuntu@server:~/vitess/examples/helm$ k3s -v 
k3s version v1.0.0 (18bd921c)
```

**Comment by morgo** [comment] 2019-12-20 17:54
Thank you for the bug report. This is a duplicate of https://github.com/vitessio/vitess/issues/5411

**Comment by gedgar** [comment] 2021-09-22 22:26
Closing this issue as the Helm charts for Vitess are [deprecated as of 7.0](https://github.com/vitessio/vitess/issues/6439).

**Closed by gedgar** 2021-09-22 22:27 UTC
Labels: Type: Bug, Status: Duplicate
