### ISSUE TITLE
Assignment operator for user-defined variables not accepted

### ISSUE THREAD

**Issue by joneug** [vitessio/vitess#10169] opened 2022-04-28 21:24 UTC
### Overview of the Issue

The [assignment operator `:=`](https://dev.mysql.com/doc/refman/8.0/en/user-variables.html) is not accepted by Vitess although such variables can be defined using `SET ...`. However, when updating variables within `SELECT` queries, only the `:=` notation can be used and not `SET...`. One use case for this is ranking queries where a row number is assigned to each row. For instance, consider the following query executed on a fresh MySQL 8 database:

```
mysql> SELECT user, host, @counter := @counter + 1 AS row_num FROM user, (SELECT @counter := 0) c ORDER BY user;
+------------------+-----------+---------+
| user             | host      | row_num |
+------------------+-----------+---------+
| mysql.infoschema | localhost |       1 |
| mysql.session    | localhost |       2 |
| mysql.sys        | localhost |       3 |
| root             | %         |       4 |
| root             | localhost |       5 |
+------------------+-----------+---------+
```

Executing the same query through Vitess leads to an error (see below).

An alternative to such use of variables for ranking purposes is the `ROW_NUMBER` function introduced in MySQL 8. Example leading to the same result as the query above:

```
SELECT user, host, ROW_NUMBER() OVER() AS row_num FROM user ORDER BY user;
```

However, this keyword is also not accepted by Vitess.

### Reproduction Steps

1. Deploy a testing cluster using the [initial cluster example](https://github.com/vitessio/vitess/blob/main/examples/operator/101_initial_cluster.yaml) provided in this repository.
2. Run
    ```
    SELECT user, host, @counter := @counter + 1 AS row_num FROM user, (SELECT @counter := 0) c ORDER BY user;
    ````
4. View error
    ```
    ERROR 1105 (HY000): syntax error at position 30 near ':'
    ```

### Binary Version

```sh
Version: 13.0.1 (Git revision f4a77b6845 branch 'heads/v13.0.1') built on Thu Apr 14 14:27:26 UTC 2022 by vitess@buildkitsandbox using go1.17.9 linux/amd64
```

### Operating System and Environment details

```sh
I run the vitess/lite:v13.0.1-mysql80 docker image on Kubernetes using the Vitess operator.

* Debian GNU/Linux 10 (buster)
* Linux 5.10.104-linuxkit
* x86_64
```

**Comment by harshit-gangal** [comment] 2022-05-02 05:07
We do not support this today.

**Comment by harshit-gangal** [comment] 2022-05-02 05:09
Duplicate of https://github.com/vitessio/vitess/issues/6595

**Closed by harshit-gangal** 2022-05-02 05:09 UTC
Labels: Type: Feature Request, Component: Query Serving
