### ISSUE TITLE
vtgate intermittently loses a tablet

### ISSUE THREAD

**Issue by tirsen** [vitessio/vitess#5229] opened 2019-09-26 05:25 UTC
We've had this lingering issue for a long time where vtgates "loose" a tablet. We've made some discoveries lately and think we have a hunch of where the issue is.

![Screen Shot 2019-09-26 at 3 15 38 PM](https://user-images.githubusercontent.com/11489/65659999-b2121800-e070-11e9-8062-6755e2741d76.png)

There should be a tablet `uswest2-0000011101` in this shard but it's missing. No matter how long we wait it will never return. If we restart the tablet it does return.

If we look in the log when there is this issue we find the following log entry in the vtgate:
```
adding duplicate tablet uswest2-0000011101 for uswest2: alias:<cell:"uswest2" uid:11101 > hostname:"10.136.93.210" port_map:<key:"grpc" value:16002 > port_map:<key:"vt" value:15002 > keyspace:"arnhem_customer" shard:"-20" key_range:<end:" " > type:SPARE db_name_override:"vt_arnhem_customer_lo_20" mysql_hostname:"REDACTED" mysql_port:3306
```

Tracing that down to the following code go/vt/discovery/healthcheck.go:736:
```
	if _, ok := hc.addrToHealth[key]; ok {
		hc.mu.Unlock()
		log.Warningf("adding duplicate tablet %v for %v: %+v", name, tablet.Alias.Cell, tablet)
		return
	}
```

Another piece of the puzzle is that this usually happens when there's been a restart. Either due to a restart of the cluster (for a redeploy) or because of a node crash or something similar.

I think the issue here is that when the tablets restart the tablet pod is allocated by Kubernetes to a node that previously ran a different tablet. That is, the node:port combo (which constitutes the `key` above) is re-used for different tablets!

I think the solution is just not to do this check. The new tablet simply overwrites the old but I'm not sure what the implications would be. Maybe the solution is just to crash and have Kubernetes restart the vtgate pod and then it will not have seen the old tablet on that node and all will be good?

It doesn't seem like we should be the only ones encountering this issue with running Vitess on Kubernetes...

**Comment by tirsen** [comment] 2019-09-26 05:37
It could also be a race condition:
```
func (hc *HealthCheckImpl) ReplaceTablet(old, new *topodatapb.Tablet, name string) {
	go func() {
		hc.deleteConn(old)
		hc.AddTablet(new, name)
	}()
}
```

There's no locks between delete and add!

**Comment by tirsen** [comment] 2019-09-26 05:39
I think this race can happen if vtgates restart at the same time as vttablets are being restarted. Then vtgate is loading the initial tablets from the topology *while* the tablet hosts are changing because of a restart of a bunch of vttablets.

**Comment by tirsen** [comment] 2019-09-26 22:31
I changed `log.Error` to `log.Fatal` and that seems to have fixed things. vtgate crashes every once in a while during a big restart and Kubernetes restarts it and it's all good.

**Comment by derekperkins** [comment] 2019-09-26 22:53
We verified that we have unknowingly been affected by this for a long time, at least as far as our log retention is concerned. This has almost definitely caused us production outages. Can we merge a PR with the `log.Fatal` fix while we decide what the long-term solution is?

**Comment by enisoc** [comment] 2019-09-26 23:09
There's a known gotcha in k8s that recently-used Pod IPs might be quickly reassigned to new Pods. If multiple tablet Pods are cycled at once, you effectively might end up with a shuffling of the tablet<->IP mappings. Many tablets might come up with IPs that recently corresponded to different tablets.

If that happens, I could see how vtgate might delete the tablet, then fail to add it back with its new address, because its new address is still being "used" by another tablet as far as vtgate knows at this time (i.e. in the `addrToHealth` map).

> Can we merge a PR with the log.Fatal fix while we decide what the long-term solution is?

I'd rather not go to that extreme, since it may cause worse problems (crash-looping) for some users.

What about if we said, if AddTablet finds a duplicate, it should overwrite with the new value, instead of dropping it? Can anyone see a case when that would be the wrong thing to do?

**Comment by tirsen** [comment] 2019-09-27 00:48
No this is a threading problem. There's a race in this code that I linked above:
```
func (hc *HealthCheckImpl) ReplaceTablet(old, new *topodatapb.Tablet, name string) {
	go func() {
		hc.deleteConn(old)
		hc.AddTablet(new, name)
	}()
}
```

I think the correct solution is either to extend the lock scope (dammit Golang with no reentrant locks) or do a more drastic refactoring where the healthcheck state is only managed by a single thread. Share-memory-by-communicating-style.

Regardless if we ever do hit that if-clause then vtgate state is corrupt and I don't think there's another option available apart from crashing. It is violating an invariant to get there.

Based on weeks of historical logs across our Vitess clusters it seems unlikely this would cause crash looping but I do have the same concern as well.

Possibly just extending the lock scope is the best way forward.

**Comment by derekperkins** [comment] 2019-09-27 00:54
If I had to choose between crash looping and living in an undetected zombie state, I'd definitely choose crashing.

**Comment by enisoc** [comment] 2019-09-27 02:53
> There's a race in this code that I linked above

I don't see how the lack of locking between `deleteConn` and `AddTablet` can lead to AddTablet hitting the `adding duplicate tablet` branch. I admit I'm new to this code, so I might be missing something obvious. Can you elaborate?

Are you saying some other goroutine can come in between them and add a different tablet with the same host? Wouldn't that still be racy if `delete-then-add` were all done while holding the lock? If the stray Add happens before the `delete-then-add`, or if the stray Add is actually a stray `delete-then-add`, then it seems like we still end up with the stray tablet winning.

> Regardless if we ever do hit that if-clause then vtgate state is corrupt

Would you consider the scenario I described a corrupt state? To me, it seems more like a valid real-world sequence of events that vtgate was not designed to handle: A tablet is added that happens to reuse the same host:port as a tablet that vtgate doesn't yet know is gone. My proposal was that vtgate should believe whichever tablet most recently claimed to be at a given host:port, and forget any previous claims on that host:port.

**Comment by enisoc** [comment] 2019-09-27 03:24
I'm investigating another trail, focused on this code:

https://github.com/vitessio/vitess/blob/eb2c7e24531c5817e68a8877b7e422bd55a2e29c/go/vt/discovery/topology_watcher.go#L244-L279

Suppose these are the existing tablets before the call to `loadTablets()`:

* tablet A: addr1
* tablet B: addr2

Now tablets A and B both have their Pods deleted and recreated. Based on how k8s assigns Pod IPs, one of them might end up reusing an IP addr that the other one was previously using:

* tablet A: addr3
* tablet B: addr1

Let's assume this is the state that `loadTablets()` sees when it reads all tablet records.

Now it enters the loop I linked above. We're going to end up calling `ReplaceTablet` for both A and B, but the order in which we make those calls is doubly random: the range loop over `newTablets` is in random order, and `ReplaceTablet()` does all its work in a new, unsynchronized goroutine.

If the ReplaceTablet on A happens first, it frees up addr1 in the `addrToHealth` map, and then the ReplaceTablet on B works as intended.

However, if the ReplaceTablet on B happens first, we remove tablet B successfully, but we fail to add it back because addr1 is still being "held" by tablet A. This is when we hit the `adding duplicate tablet` code path.

**Closed** 2019-09-27 17:29 UTC
