### ISSUE TITLE
`docker/test/run.sh` doesn't work on macOS

### ISSUE THREAD

**Issue by guidoiaquinti** [vitessio/vitess#5772] opened 2020-01-28 11:06 UTC
#### Overview of the Issue
`docker/test/run.sh` doesn't work on macOS. 

The script [is trying to mount](https://github.com/vitessio/vitess/blob/aeab98e0c026717c990596f827ad9e10277602e3/docker/test/run.sh#L132) `/dev/log` that doesn't exist on macOS. We should probably use `/var/run/syslog`.

#### Reproduction Steps
Run `docker/test/run.sh mysql57 "make build"` on macOS.

#### Operating system and Environment details

- Operating system: `macOS Catalina 10.15.1`
- Kernel version (output of `uname -sr`): `Darwin 19.0.0`
- Architecture (output of `uname -m`): `x86_64`

#### Log Fragments
It's true that the shared paths are not configured in my setup but the path doesn't exist anyway:
```
Digest: sha256:80e92d26248c1bd55d7119da429242e3a6f71cadfbd187d1b71e3463713cf5e4
Status: Downloaded newer image for vitess/bootstrap:mysql57
docker: Error response from daemon: Mounts denied:
The path /dev/log
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

**Comment by saifalharthi** [comment] 2020-02-05 23:13
@guidoiaquinti I change that line to `/private/var/run:/dev/log` to work around that.

**Comment by gedgar** [comment] 2021-09-22 23:18
Closing this issue as it doesn't appear to be an issue on `main`, unable to reproduce via: 
```
docker/test/run.sh mysql57 3 "make build"
```

I'll get a PR in to fix the examples in `docker/test/run.sh` to reflect the bootstrap versioning changes from https://github.com/vitessio/vitess/pull/7182.

**Closed by gedgar** 2021-09-22 23:18 UTC
Labels: Type: Bug, Good First Issue
