### ISSUE TITLE
Bug Report: Waiting for semi-sync ACK blocks backup from primary tablet

### ISSUE THREAD

**Issue by yydoow** [vitessio/vitess#16380] opened 2024-07-15 01:58 UTC
### Overview of the Issue

When all the replicas of a shard become not serving, primary vttablet becomes `read only` given no ack from any of replica.
In this case xtrabackup can not get lock for binlog by `LOCK BINLOG FOR BACKUP`. The backup process is in the loop `log scanned up to XX` after the lock acquisition forever till some timeout

### Reproduction Steps

* Setup a keyspace with semi_sync and heartbeat enabled and mysql config
```
innodb-rollback-on-timeout: ON
innodb-lock-wait-timeout: 5
lock-wait-timeout: 5
```
* Kill the replication on replicas, then the primary become sort of read only
* On the primary you will see following `Waiting for semi-sync ACK `from show processlist
```
Waiting for semi-sync ACK from slave | INSERT INTO _vt.heartbeat (ts, tabletUid, keyspaceShard) VALUES (1720576630432517681, 2544605171, 'achievementsengine_user:e4-e6') ON DUPLICATE KEY UPDATE ts=VALUES(ts), tabletUid=VALUES(tabletUid)
```
* Run `LOCK BINLOG FOR BACKUP`,  it will be restarted after lock-wait-timeout
```
mysql> show global variables like '%semi%';
+-------------------------------------------+---------------------+
| Variable_name                             | Value               |
+-------------------------------------------+---------------------+
| rpl_semi_sync_master_enabled              | ON                  |
| rpl_semi_sync_master_timeout              | 1000000000000000000 |
| rpl_semi_sync_master_trace_level          | 32                  |
| rpl_semi_sync_master_wait_for_slave_count | 1                   |
| rpl_semi_sync_master_wait_no_slave        | ON                  |
| rpl_semi_sync_master_wait_point           | AFTER_SYNC          |
| rpl_semi_sync_slave_enabled               | ON                  |
| rpl_semi_sync_slave_trace_level           | 32                  |
+-------------------------------------------+---------------------+
8 rows in set (0.00 sec)
```
* Start backup from the primary. it keeps looping on `log scanned up to XX`
```
backup stderr: 240712 08:24:47 Finished backing up non-InnoDB tables and files
I0712 16:24:48.256398   47584 main.go:96] I0712 08:24:47.859474 backup.go:108] I0712 08:24:47.859398 xtrabackupengine.go:369] xtrabackup stderr: 240712 08:24:47 Executing LOCK BINLOG FOR BACKUP...
I0712 16:24:48.256406   47584 main.go:96] I0712 08:24:47.859484 backup.go:108] I0712 08:24:47.859408 xtrabackupengine.go:369] xtrabackup stderr: 240712 08:24:47 >> log scanned up to (42205617305484)
I0712 16:24:48.594902   47584 main.go:96] I0712 08:24:48.864258 backup.go:108] I0712 08:24:48.864150 xtrabackupengine.go:369] xtrabackup stderr: 240712 08:24:48 >> log scanned up to (42205618620733)
```
* run `set global rpl_semi_sync_master_enabled = off;` on the primary, then the backup is finished right away.
The backup process needs to know if the primary become "readonly" due to lack of ACK from semi_sync after `LOCK BINLOG FOR BACKUP` is issued,  it has the change to `set global rpl_semi_sync_master_enabled = off;` on the primary to unblock the backup and revert the change back when the backup is finished.

### Binary Version

```sh
v16.0.2
Server version: 5.7.43-47-log Percona Server (GPL), Release '47', Revision 'ff1a4d42212'
```

### Operating System and Environment details

```sh
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
vitess@vitess-db-vttablet-las-0132278012-3c3a632d:/$ uname -sr)
bash: syntax error near unexpected token `)'
vitess@vitess-db-vttablet-las-0132278012-3c3a632d:/$ uname -sr
Linux 6.1.0-20-amd64
vitess@vitess-db-vttablet-las-0132278012-3c3a632d:/$ uname -m
x86_64
```

**Comment by mattlord** [comment] 2024-07-15 22:32
I'm not sure that disabling semi-sync is necessarily the right thing to do here, but having this as optional behavior could certainly make sense. /cc @GuptaManan100

**Comment by GuptaManan100** [comment] 2024-07-16 04:30
I'm not sure if I'll even file this as a bug at all. If the cluster is running with the `semi_sync` durability policy and has no replicas that can send those ACKs, then it is in a degraded state. You should be bringing up replicas that can send the acks to fix things. 

If for some reason you only want the backup to succeed irrespective of anything else, then you should change the durability policy to `none` which will turn off primary side semi-sync and the backup will succeed. It is not safe for Vitess to turn off semi-sync when the durability policy is `semi_sync` under any circumstances. Because it can lead to the primary accepting writes that aren't available on any other replica, breaking the guarantee you get from using the `semi_sync` durability policy.

If you have any other concerns please let us know and we can discuss it further. For now, I am closing the issue because this is the expected behaviour.

**Closed by GuptaManan100** 2024-07-16 04:30 UTC
Labels: Type: Bug, Type: Enhancement, Component: Backup and Restore

**Comment by yydoow** [comment] 2024-07-16 08:37
In this case, if the binlogs is purged on the primary, then the replica is no longer able to recover from the backup.
without backup we are not able to recover the replica, then chicken and egg issue.

So we will have to temporary disable `semi_sync` to make a backup, this could trigger a reparenting when the primary is restarted, however either of the replicas in our case have less data than the primary become the primary, application keep writing data into the new primary which data is out of sync.

Would be possible to make a backup from the primary and guarantee  `semi-sync` ?

**Comment by deepthi** [comment] 2024-07-16 14:26
In your reproduction, semi-sync is stuck waiting for an ACK for a heartbeat write. Is this what you always see? The point is that if there's an application write that the primary is waiting on, then it is not possible for Vitess to know whether it is safe to disable semi-sync to take a backup. Whereas you as the administrator of the cluster can make the decision to manually turn off semi-sync on the primary because you know what else is happening in the system.

**Comment by yydoow** [comment] 2024-07-17 01:35
Could it be a feature request? like ` Backup -- --concurrency=1 --allow_primary --disable_semi_sync $tablet`
So it easier for administrator to carry out a backup ?

**Comment by yydoow** [comment] 2024-07-18 06:14
@deepthi

**Comment by deepthi** [comment] 2024-07-30 17:14
This is really a situation where the administrator needs to perform manual actions. For example, what if vtorc is running? You may need to turn that off before turning off semi-sync. Adding such flags and features will just lead to other failure scenarios. My recommendation is to develop a playbook to dig yourselves out of the situation. Once you have that, you are welcome to present your solution at one of our community meetings, and at that time we can evaluate whether some of your learnings can be contributed back to the project as emergency tooling.
