### ISSUE TITLE
Bug Report: IFNULL not supported when used with a join

### ISSUE THREAD

**Issue by olyazavr** [vitessio/vitess#11242] opened 2022-09-16 13:54 UTC
### Overview of the Issue

I have a query with IFNULL that fails with the error `expr cannot be converted, not supported: IFNULL(:__sq1, :v6)" code: UNIMPLEMENTED`. This works just fine in Vitess 5, but breaks in Vitess 13. I've noticed that other queries with IFNULL work, but this particular one does not- debugging further shows me that it's when the query also has a JOIN that the IFNULL breaks.

From my debugging it seems like when there is a join, we get [here](https://github.com/vitessio/vitess/blob/bc4a9606e1899a4223b80edfb212f32af81000ac/go/vt/vtgate/planbuilder/operator_transformers.go#L69) where it tries to convert `a.notification_action is null and n.created_at > IFNULL(:__sq1, :v6)` which leads us to the [case statement on node type](https://github.com/vitessio/vitess/blob/bc4a9606e1899a4223b80edfb212f32af81000ac/go/vt/vtgate/evalengine/convert.go#L189) for which this expression, `IFNULL(:__sq1, :v6)`, doesn't have a case [so it errors](https://github.com/vitessio/vitess/blob/bc4a9606e1899a4223b80edfb212f32af81000ac/go/vt/vtgate/evalengine/convert.go#L381). Without the join, the IFNULL doesn't get `convert`ed, so we don't go down this code path at all and it succeeds

### Reproduction Steps

VSchema:
```
{
  "sharded": true,
  "vindexes": {
    "hash": {
      "type": "hash"
    }
  },
  "tables": {
    "actions": {
      "columnVindexes": [
        {
          "column": "portal_id",
          "name": "hash"
        }
      ]
    },
    "last_shown_notification": {
      "columnVindexes": [
        {
          "column": "portal_id",
          "name": "hash"
        }
      ]
    },
    "notifications": {
      "columnVindexes": [
        {
          "column": "portal_id",
          "name": "hash"
        }
      ],
      "autoIncrement": {
        "column": "id",
        "sequence": "Notifications__notifications__id__seq"
      }
    }
  }
}
```

Schema:
```
CREATE TABLE `notifications` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned NOT NULL,
  `portal_id` int(10) unsigned NOT NULL,
  `type` bigint(20) unsigned NOT NULL,
  `template` bigint(20) unsigned NOT NULL,
  `origin` bigint(20) unsigned NOT NULL,
  `created_at` bigint(20) unsigned NOT NULL COMMENT 'Millisecond timestamp',
  `cta_url` text COLLATE utf8mb4_unicode_ci,
  `idempotency_id` varchar(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `process_id` binary(16) NOT NULL COMMENT 'UUID. Prevents kafka duplicates.',
  `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `display_in_notification_center` tinyint(1) unsigned NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idempotency_id` (`idempotency_id`),
  UNIQUE KEY `process_id` (`process_id`),
  KEY `email_portal_id_created_at` (`email`,`portal_id`,`created_at`),
  KEY `template_origin_created_at` (`origin`,`template`,`created_at`),
  KEY `portal_id_created_at` (`portal_id`,`created_at`),
  KEY `portal_id_template_id` (`portal_id`,`template`),
  KEY `user_id_portal_id_created_at` (`user_id`,`portal_id`,`created_at`),
  KEY `user_id_portal_id_display_in_notification_center_created_at` (`user_id`,`portal_id`,`display_in_notification_center`,`created_at`),
  KEY `user_id_portal_id_type_created_at` (`user_id`,`portal_id`,`type`,`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=22536756579 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8

CREATE TABLE `actions` (
  `notification_id` bigint(20) unsigned NOT NULL,
  `delivery_method` tinyint(3) unsigned NOT NULL,
  `notification_action` tinyint(3) unsigned NOT NULL,
  `created_at` bigint(20) unsigned NOT NULL COMMENT 'Millisecond timestamp',
  `db_record_created` datetime DEFAULT CURRENT_TIMESTAMP COMMENT 'Do not set manually! Generated by the database whenever an entry is created',
  `portal_id` int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (`notification_id`,`delivery_method`,`notification_action`),
  KEY `db_record_created` (`db_record_created`),
  KEY `actions_portal_id_created_at_index` (`portal_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8

CREATE TABLE `last_shown_notification` (
  `user_id` int(10) unsigned NOT NULL,
  `portal_id` int(10) unsigned NOT NULL,
  `notification_id` bigint(20) unsigned NOT NULL,
  `db_record_updated` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'Do not set manually! Generated by the database whenever an entry is created',
  `db_record_created` datetime(6) DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'Do not set manually! Generated by the database whenever an entry is created',
  `created_at` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`user_id`,`portal_id`),
  KEY `notification_id` (`notification_id`),
  KEY `last_shown_notification_updated_index` (`db_record_updated`),
  KEY `lsn_portal_id_created_at_index` (`portal_id`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=COMPRESSED KEY_BLOCK_SIZE=8
```

Query:
```
SELECT n.id FROM notifications AS n 
LEFT JOIN actions a ON a.notification_id = n.id AND n.portal_id = a.portal_id  
WHERE n.user_id = :user_id AND n.portal_id = :portal_id  
AND n.display_in_notification_center = 1 AND a.notification_action IS NULL  
AND n.created_at > (  
SELECT IFNULL(  
(SELECT created_at FROM notifications WHERE id = (SELECT notification_id FROM last_shown_notification WHERE user_id = :user_id AND portal_id = :portal_id) and portal_id = :portal_id),  
(:backAsFarAs))  
) ORDER BY n.created_at ASC, n.id ASC LIMIT 100
```

If you remove the JOIN and instead do:
```
SELECT n.id FROM notifications AS n 
WHERE n.user_id = :user_id AND n.portal_id = :portal_id  
AND n.display_in_notification_center = 1 
AND n.created_at > (  
SELECT IFNULL(  
(SELECT created_at FROM notifications WHERE id = (SELECT notification_id FROM last_shown_notification WHERE user_id = :user_id AND portal_id = :portal_id) and portal_id = :portal_id),  
(:backAsFarAs))  
) ORDER BY n.created_at ASC, n.id ASC LIMIT 100
```

this version works, but we need the JOIN

The rewritten query is interesting, it has a `from dual` in it that is not present in the original query:
`select /*+ MAX_EXECUTION_TIME(30000) */ n.id from notifications as n left join actions as a on a.notification_id = n.id and n.portal_id = a.portal_id where n.user_id = :v1 and n.portal_id = :v2 and n.display_in_notification_center = :redacted1 and a.notification_action is null and n.created_at > (select IFNULL((select created_at from notifications where id = (select notification_id from last_shown_notification where user_id = :v3 and portal_id = :v4) and portal_id = :v5), :v6) from dual) order by n.created_at asc, n.id asc limit :redacted2`

### Binary Version

```sh
v13.0.0, commit bc4a960
```

### Operating System and Environment details

```sh
Can repro on both macos and linux, running unit tests in Java
```

### Log Fragments

```sh
org.skife.jdbi.v2.exceptions.UnableToExecuteStatementException: java.sql.SQLNonTransientException: Vitess vtgate error: message: "expr cannot be converted, not supported: IFNULL(:__sq1, :v6)"
code: UNIMPLEMENTED
 [statement:"SELECT n.id FROM notifications AS n LEFT JOIN actions a ON a.notification_id = n.id AND n.portal_id = a.portal_id WHERE n.user_id = :user_id AND n.portal_id = :portal_id AND n.display_in_notification_center = 1 AND a.notification_action IS NULL AND n.created_at > ( SELECT IFNULL( (SELECT created_at FROM notifications WHERE id = (SELECT notification_id FROM last_shown_notification WHERE user_id = :user_id AND portal_id = :portal_id) and portal_id = :portal_id), (:backAsFarAs)) ) ORDER BY n.created_at ASC, n.id ASC LIMIT 100", located:"SELECT n.id FROM notifications AS n LEFT JOIN actions a ON a.notification_id = n.id AND n.portal_id = a.portal_id WHERE n.user_id = :user_id AND n.portal_id = :portal_id AND n.display_in_notification_center = 1 AND a.notification_action IS NULL AND n.created_at > ( SELECT IFNULL( (SELECT created_at FROM notifications WHERE id = (SELECT notification_id FROM last_shown_notification WHERE user_id = :user_id AND portal_id = :portal_id) and portal_id = :portal_id), (:backAsFarAs)) ) ORDER BY n.created_at ASC, n.id ASC LIMIT 100", rewritten:"SELECT /*+ MAX_EXECUTION_TIME(30000) */ n.id FROM notifications AS n LEFT JOIN actions a ON a.notification_id = n.id AND n.portal_id = a.portal_id WHERE n.user_id = ? AND n.portal_id = ? AND n.display_in_notification_center = 1 AND a.notification_action IS NULL AND n.created_at > ( SELECT IFNULL( (SELECT created_at FROM notifications WHERE id = (SELECT notification_id FROM last_shown_notification WHERE user_id = ? AND portal_id = ?) and portal_id = ?), (?)) ) ORDER BY n.created_at ASC, n.id ASC LIMIT 100", arguments:{ positional:{}, named:{user_id:2424,portal_id:3535,backAsFarAs:1660744465370}, finder:[]}]
```

**Comment by systay** [comment] 2022-10-03 08:26
Hi @olyazavr!

Thanks for reporting this. I'm trying to reproduce this, but the query is referencing `last_shown_notification` which wasn't included in the vschema/schema. Do you happen to have them available?

**Comment by olyazavr** [comment] 2022-10-03 10:54
Ah my bad, I've added it in

**Comment by systay** [comment] 2022-10-04 10:07
Hmm... I can't seem to be able to reproduce your issue. Not sure why that is - could be related to the left join fix that recently went in. Could you try to reproduce again and see if it's fixed for you?

I did [add code](https://github.com/vitessio/vitess/pull/11431) to support IFNULL in the evalengine as well, but you should not need to.

**Comment by olyazavr** [comment] 2022-10-04 10:36
I tried on Sept 20 with the latest of v13 and still had this issue, but haven't tried since. We moved to v14 and haven't seen this there, and I no longer have the v13 testing setup around, sorry 😓 
If it's important, I can resurrect it, but I'm away until next week

**Comment by systay** [comment] 2022-10-04 13:54
Cool. If you are not seeing the problem, and I'm unable to reproduce, let's close this issue for now.

Thanks again!

**Closed by systay** 2022-10-04 13:54 UTC
Labels: Type: Bug, Component: Query Serving
