### ISSUE TITLE
(wr *Wrangler) ShardReplicationStatuses hangs forever

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#4572] opened 2019-01-30 18:33 UTC
I'm indirectly using `ShardReplicationStatuses` via `BackupShard`, and I found a case where it hangs forever. I spun up some `rdonly` tablets temporarily, but when I deleted them, they didn't remove their tablet records. That left references with bad host names. I would expect for the call to either return an error that it couldn't contact one of the tablets, but instead, it hangs there until the context timeout hits, which is a couple hours by default for the backup call. 

https://github.com/vitessio/vitess/blob/744b8e2ea882f0dbd6eae38393b584503ab2165e/go/vt/wrangler/reparent.go#L78-L90

It looks like the actual backup is timing out, which led me to set the `action_timeout` to 6 hours, which made it harder to diagnose the problem. It would have been much nicer to see an error about not being able to connect to a tablet to get the replication status. I haven't dug deeper yet into the `SlaveStatus` interface call to see where that is set.

I'm not sure if tweaking the behavior of that call is appropriate or if it will have more cascading effects elsewhere that expect it to wait forever.

**Comment by ajm188** [comment] 2022-06-24 14:04
This is a dupe of #4073, and I fixed this in https://github.com/vitessio/vitess/pull/7690, so going to close!

**Closed by ajm188** 2022-06-24 14:04 UTC
Labels: Type: Bug, Component: Cluster management
