### ISSUE TITLE
Pass `--defaults-extra-file` as first argument to xtrabackup

### ISSUE THREAD

**Issue by sverch** [vitessio/vitess#5345] opened 2019-10-23 18:04 UTC
#### Feature Description

From https://www.percona.com/doc/percona-xtrabackup/2.3/xtrabackup_bin/xbk_option_reference.html:

> --defaults-extra-file=[MY.CNF]
> 
>     Read this file after the global files are read. Must be given as the first option on the command-line.

However, the flags are all appended: https://github.com/vitessio/vitess/blob/master/go/vt/mysqlctl/xtrabackupengine.go#L212

That means this file can't be passed into xtrabackup.

#### Use Case(s)

Putting the password for the backup user in that file: https://www.percona.com/forums/questions-discussions/percona-xtrabackup/8625-password-in-defaults-extra-file

**Comment by morgo** [comment] 2019-10-23 21:37
cc @deepthi

**Comment by deepthi** [comment] 2019-10-24 19:41
We are already passing `--defaults-file` as the first option. If we believe the docs, we cannot pass `--defaults-extra-file` and `--defaults-file` together because you can't have two first options. We have reason to not believe the docs, so this is definitely worth trying.
One way to do it is to parse and extract `--defaults-extra-file` from xtrabackupBackupFlags. The other way is to add a separate command line option for the extra file.

**Comment by deepthi** [comment] 2019-11-07 17:17
Actually you can't use both `--defaults-file` and `--defaults-extra-file` with xtrabackup:
```
~/go/src/vitess.io/vitess$ xtrabackup --defaults-file=~/go/vtdataroot/vt_0000000655/my.cnf --defaults-extra-file=my.cnf --backup
xtrabackup: Error: --defaults-extra-file must be specified first on the command line
~/go/src/vitess.io/vitess$ xtrabackup --defaults-extra-file=my.cnf --defaults-file=~/go/vtdataroot/vt_0000000655/my.cnf --backup
xtrabackup: Error: --defaults-file must be specified first on the command line
```

**Comment by hwang381** [comment] 2019-11-30 22:18
First time contributor here :wave: 
Looks like an easy fix would be to respect the cli interface of `xtrabackup`, add an option to pass in `--defaults-extra-file` and make it mutually exclusive with `--defaults-file`. May I take a look at this if this sounds right to you? @deepthi

**Comment by deepthi** [comment] 2019-12-03 02:25
welcome @hwang381!
the problem is that we are already invoking xtrabackup with `--defaults-file` so that we can pass in the configuration that we are running mysql with, so we don't really have the choice of allowing `--defaults-extra-file`.

**Comment by sverch** [comment] 2019-12-09 17:51
I filed this with Percona: https://jira.percona.com/browse/PXB-1975

I'm not sure if there's anything for us to do here.

**Comment by Anders-PlanetScale** [comment] 2021-09-23 17:00
Closing this out, since Percona JIRA/Bug report is still outstanding 2 years later.

I have created  PR to document the recommended xtrabackup auth configuration https://github.com/vitessio/website/pull/833

**Closed by Anders-PlanetScale** 2021-09-23 17:00 UTC
Labels: Type: Enhancement, Component: Cluster management
