### ISSUE TITLE
Test Common Connectors and Frameworks

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#5166] opened 2019-09-06 17:53 UTC
#### Overview of the Issue

We should prioritize adding support for SQL statements that are executed by common connectors and frameworks/ORMs.

I suggest handling this in two steps:

1. We run the common frameworks against a regular MySQL 5.7 server and log the queries. The captured queries are then included in unit tests.

2. We write an extended testing framework to actually execute these frameworks against Vitess (on a weekly basis etc.)

## For initial support

- [x] phpmyadmin
- [x] django
- [x] mysqldump (restoring breaks due to session vars, #5402, #5403).
- [x] Jira
- [x] Dbeaver
- [x] Rust - sqlx
- [x] Wordpress
- [x] MySQL workbench
- [x] gorm
- [x] Ruby on Rails / Active Record
- [x] JDBC
- [x] Hibernate
- [x] SQLAlchemy
- [x] mycli
- [x] PyMySQL
- [x] Rust - MySQL
- [x] JavaScript - TypeORM
- [x] JavaScript - Sequelize
- [ ] Drupal: fails, cause unknown (see below)
- [ ] Liquibase
- [ ] SequelPro

Others can be added later (MySQL Workbench, etc)

## Known Issues

~~#6647 - SET GLOBAL support~~
~~#5205 - MySQL JDBC driver tries to send "select @@query_cache_size as query_cache_size from dual;"~~
#5392 - Wordpress Install error on multi-table delete query
~~#5402 - LOCK/UNLOCK TABLES statement~~
#5403 - mysqldump: server with gtids

**Comment by saifalharthi** [comment] 2019-09-06 18:49
question to all: Is there any other ORMs that we need to account for? if so, please add a comment.

**Comment by aquarapid** [comment] 2019-09-18 16:06
C# connector too.  See #5201

**Comment by parthibd** [comment] 2019-09-18 18:39
Laravel Eloquent ORM

**Comment by mc0** [comment] 2019-10-07 19:06
Just adding one to the pile: [TypeORM](https://github.com/typeorm/typeorm)

**Comment by aford4074** [comment] 2019-10-10 23:38
Adding jOOQ to the list.

**Comment by rajveerappan** [comment] 2019-10-30 16:44
[FlyWay](https://flywaydb.org/) is popular for migrations

**Comment by morgo** [comment] 2019-11-01 16:13
Drupal fails with the following error:
```
[Fri Nov  1 10:08:34 2019] Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[HY000]: General error: 1105 vtgate: http://morgox1:15001/: syntax error at position 25: INSERT INTO {sequences} () VALUES (); Array
(
)
 in /home/morgo/wordpress/drupal-8.7.8/core/includes/form.inc on line 840 #0 /home/morgo/wordpress/drupal-8.7.8/core/lib/Drupal/Core/Database/Connection.php(656): Drupal\Core\Database\Connection->handleQueryException(Object(PDOException), 'INSERT INTO {se...', Array, Array)
#1 /home/morgo/wordpress/drupal-8.7.8/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(358): Drupal\Core\Database\Connection->query('INSERT INTO {se...', Array, Array)
#2 /home/morgo/wordpress/drupal-8.7.8/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(585): Drupal\Core\Database\Driver\mysql\Connection->query('INSERT INTO {se...', Array, Array)
#3 /home/morgo/wordpress/drupal-8.7.8/core/includes/form.inc(840): Drupal\Core\Database\Driver\mysql\Connection->nextId()
#4 /home/morgo/wordpress/drupal-8.7.8/core/includes/install.core.inc(659): batch_process(Object(Drupal\Core\Url), Object(Drupal\Core\Url))
#5 /home/morgo/wordpress/drupal-8.7.8/core/includes/install.core.inc(577): install_run_task(Array, Array)
#6 /home/morgo/wordpress/drupal-8.7.8/core/includes/install.core.inc(118): install_run_tasks(Array, NULL)
#7 /home/morgo/wordpress/drupal-8.7.8/core/install.php(44): install_drupal(Object(Composer\Autoload\ClassLoader))
#8 {main}
```
Note that this query would be an error in MySQL too, so it is likely a select query prior returned the wrong response:
```
mysql80> INSERT INTO {sequences} () VALUES (); 
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{sequences} () VALUES ()' at line 1
```

**Comment by mcronce** [comment] 2019-11-14 20:29
Piwigo mostly works, but _some_ operations fail, looks like #3904 

```
[mysql error 1105] vtgate: syntax error at position 32

SELECT SQL_CALC_FOUND_ROWS com.id AS comment_id,
       com.image_id,
       ic.category_id,
       com.author,
       com.author_id,
       u.mail_address AS user_email,
       com.email,
       com.date,
       com.website_url,
       com.content,
       com.validated
  FROM piwigo_image_category AS ic
    INNER JOIN piwigo_comments AS com
    ON ic.image_id = com.image_id
    LEFT JOIN piwigo_users As u
    ON u.id = com.author_id
  WHERE 1=1
    AND  1 = 1
  GROUP BY comment_id
  ORDER BY date DESC
  LIMIT 10 OFFSET 0
;
```

The same query without `SQL_CALC_FOUND_ROWS` works fine.

**Comment by saifalharthi** [comment] 2019-11-14 20:33
@mcronce We have an issue for `SQL_CALC_FOUND_ROWS` https://github.com/vitessio/vitess/issues/3904

**Comment by mcronce** [comment] 2019-11-14 21:09
I see Django mentioned in the original issue but didn't find anything that seemed to call this out specifically

Trying to run Mayan EDMS, which is Django-based, results in the following on startup:

```
mayan: starting entrypoint.sh
mayan: update_uid_gid()
mayan: os_package_installs()
mayan: pip_installs()
mayan: initialize()
JSONField implementation is: <class 'django.db.models.fields.TextField'>
Operations to perform:
  Apply all migrations: acls, actstream, admin, auth, authtoken, autoadmin, cabinets, checkouts, common, contenttypes, converter, django_gpg, djcelery, document_comments, document_indexing, document_parsing, document_signatures, document_states, documents, dynamic_search, events, file_metadata, linking, lock_manager, mailer, mayan_statistics, metadata, motd, ocr, permissions, sessions, sites, sources, tags, user_management
Running migrations:
  Applying permissions.0002_auto_20150628_0533...Traceback (most recent call last):
  File "/opt/mayan-edms/bin/mayan-edms.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/mayan/apps/common/management/commands/initialsetup.py", line 89, in handle
    pre_initial_setup.send(sender=self)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
    for receiver in self._live_receivers(sender)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/mayan/apps/common/handlers.py", line 10, in handler_pre_initial_setup
    management.call_command(command_name='migrate', interactive=False)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 156, in database_forwards
    schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 479, in remove_field
    fk_names = self._constraint_names(model, [field.column], foreign_key=True)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 1011, in _constraint_names
    constraints = self.connection.introspection.get_constraints(cursor, model._meta.db_table)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/backends/mysql/introspection.py", line 182, in get_constraints
    cursor.execute(name_query, [table_name])
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
    return self.cursor.execute(query, args)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/mayan-edms/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.OperationalError: (1105, 'vtgate: symbol kc.table_schema not found')
```

**Comment by mcronce** [comment] 2019-11-14 23:59
Firefly III, which is built on Laravel, fails to install/migrate with the following query:

```sql
SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage      k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'rule_groups' */ WHERE k.table_name = 'rule_groups' AND k.table_schema = 'firefly' /*!50116 AND c.constraint_schema = 'firefly' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL;
```

#5394 is probably the cause

**Comment by mcronce** [comment] 2019-11-15 00:10
Kimai 2, whose database interaction is done through Doctrine as part of the Symfony framework, fails to install with a virtually identical query

**Comment by aquarapid** [comment] 2019-12-06 23:14
mysqldump actually fails for additional reasons (you can disable the network timeout):

```
mysqldump -u root -P 15306 customer -h 127.0.0.1 --skip-network-timeout --lock-tables=off --quote-names
mysqldump: Error: 'vtgate: http://localhost:15001/: no keyspace in database name specified. Supported database name format (items in <> are optional): keyspace<:shard><@type> or keyspace<[range]><@type>' when trying to dump tablespaces
mysqldump: Couldn't execute 'SET SQL_QUOTE_SHOW_CREATE=1': vtgate: http://localhost:15001/: unsupported construct: SET SQL_QUOTE_SHOW_CREATE=1 (1105)
```

i.e. we don't support `SET SQL_QUOTE_SHOW_CREATE`.

There's no way to disable that (at least in the mysqldump from MySQL 8.0.18)

**Comment by jawabuu** [comment] 2020-04-10 06:12
> I see Django mentioned in the original issue but didn't find anything that seemed to call this out specifically
> 
> Trying to run Mayan EDMS, which is Django-based, results in the following on startup:
> 
> ```
> mayan: starting entrypoint.sh
> mayan: update_uid_gid()
> mayan: os_package_installs()
> mayan: pip_installs()
> mayan: initialize()
> JSONField implementation is: <class 'django.db.models.fields.TextField'>
> Operations to perform:
>   Apply all migrations: acls, actstream, admin, auth, authtoken, autoadmin, cabinets, checkouts, common, contenttypes, converter, django_gpg, djcelery, document_comments, document_indexing, document_parsing, document_signatures, document_states, documents, dynamic_search, events, file_metadata, linking, lock_manager, mailer, mayan_statistics, metadata, motd, ocr, permissions, sessions, sites, sources, tags, user_management
> Running migrations:
>   Applying permissions.0002_auto_20150628_0533...Traceback (most recent call last):
>   File "/opt/mayan-edms/bin/mayan-edms.py", line 10, in <module>
>     execute_from_command_line(sys.argv)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
>     utility.execute()
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
>     output = self.handle(*args, **options)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/mayan/apps/common/management/commands/initialsetup.py", line 89, in handle
>     pre_initial_setup.send(sender=self)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send
>     for receiver in self._live_receivers(sender)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/mayan/apps/common/handlers.py", line 10, in handler_pre_initial_setup
>     management.call_command(command_name='migrate', interactive=False)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 131, in call_command
>     return command.execute(*args, **defaults)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
>     output = self.handle(*args, **options)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 204, in handle
>     fake_initial=fake_initial,
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 115, in migrate
>     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
>     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
>     state = migration.apply(state, schema_editor)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 129, in apply
>     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 156, in database_forwards
>     schema_editor.remove_field(from_model, from_model._meta.get_field(self.name))
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 479, in remove_field
>     fk_names = self._constraint_names(model, [field.column], foreign_key=True)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 1011, in _constraint_names
>     constraints = self.connection.introspection.get_constraints(cursor, model._meta.db_table)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/backends/mysql/introspection.py", line 182, in get_constraints
>     cursor.execute(name_query, [table_name])
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
>     six.reraise(dj_exc_type, dj_exc_value, traceback)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 101, in execute
>     return self.cursor.execute(query, args)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
>     self.errorhandler(self, exc, value)
>   File "/opt/mayan-edms/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
>     raise errorclass, errorvalue
> django.db.utils.OperationalError: (1105, 'vtgate: symbol kc.table_schema not found')
> ```

@mcronce Could you try the custom backend here and let me know if you still have an issue
https://github.com/vitessio/vitess/tree/master/support/django

**Comment by systay** [comment] 2020-10-13 05:56
FYI - We have updated this issue to reflect the current state of things

**Comment by kirantpatil** [comment] 2020-12-28 07:56
Any updates on "Ruby on Rails / Active Record" support ?

Is it available for testing ?

**Comment by harshit-gangal** [comment] 2020-12-28 15:55
@kirantpatil you should be able to use it without any issues. Also, if you find any then log an issue.

**Comment by kirantpatil** [comment] 2020-12-28 16:12
@harshit-gangal, Great. Thanks a lot.

**Comment by parthibd** [comment] 2020-12-28 16:25
Will we get support for Laravel ?

**Comment by harshit-gangal** [comment] 2020-12-28 16:30
@parthibd If you are able to log issues on using Laravel we can take a look and fix them.

**Comment by jondcallahan** [comment] 2021-05-24 19:23
[Prisma](https://github.com/prisma/prisma) support would be 💯

**Comment by harshit-gangal** [comment] 2021-11-15 09:13
I am going to close the issue as we have covered basic test around almost all the frameworks and we have 100% coverage on Rails and Django testing.
Anyone can open a new issue on framework incompatible query as separate issue.

**Closed by harshit-gangal** 2021-11-15 09:13 UTC
Labels: Type: Enhancement
