### ISSUE TITLE
last_insert_id is broken

### ISSUE THREAD

**Issue by systay** [vitessio/vitess#5417] opened 2019-11-07 13:36 UTC
When filing a bug, please include the following headings if
possible. Any example text in this template can be deleted.

#### Overview of the Issue

The following query was recently made illegal in Vitess (since the merge of #5268)

```SELECT last_insert_id()``` 

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Deploy the following `vschema`:

```
{
	"sharded": false,
	"tables": {
		"messages": {},
		"tokens": {}
	}
}
```

1. Deploy the following `schema`:

```
CREATE TABLE t (id INTEGER AUTO_INCREMENT PRIMARY KEY, f VARCHAR(1));
```

2. Insert data using this query:
```
INSERT INTO t(f) VALUES('a');
```

3. Try to view the inserted auto incremented id:
```
SELECT last_insert_id()
```

you'll see the error: `unsupported: LAST_INSERT_ID is only allowed for unsharded keyspaces`

I believe this is not the correct behaviour. I did a little writeup of how LII() is supposed to work here: https://gist.github.com/systay/09240a11ec12d3c63c48b39e1b47969b

**Comment by morgo** [comment] 2019-11-07 14:05
I believe this is a duplicate of: https://github.com/vitessio/vitess/issues/3668

I would love to see it fixed too.

**Comment by systay** [comment] 2019-11-07 14:39
It's not strictly a duplicate - the `last_insert_id` situation took a turn for the worse last week with the change of how it is handled against `dual`.

**Closed** 2020-01-07 23:11 UTC
Labels: Type: Bug
