### ISSUE TITLE
data race in wrangler test

### ISSUE THREAD

**Issue by sougou** [vitessio/vitess#5985] opened 2020-03-27 22:12 UTC
```
020-03-27T18:51:26.5061647Z ==================
2020-03-27T18:51:26.5062076Z WARNING: DATA RACE
2020-03-27T18:51:26.5062263Z Read at 0x00000236bdf8 by goroutine 176:
2020-03-27T18:51:26.5062459Z   vitess.io/vitess/go/vt/wrangler.init.1.func1()
2020-03-27T18:51:26.5062699Z       /home/runner/work/vitess/vitess/go/vt/wrangler/vdiff_env_test.go:69 +0x62
2020-03-27T18:51:26.5062926Z   vitess.io/vitess/go/vt/discovery.(*healthCheckConn).stream()
2020-03-27T18:51:26.5063172Z       /home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:614 +0x55f
2020-03-27T18:51:26.5063405Z   vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).checkConn()
2020-03-27T18:51:26.5063635Z       /home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:545 +0x496
2020-03-27T18:51:26.5063734Z 
2020-03-27T18:51:26.5063922Z Previous write at 0x00000236bdf8 by goroutine 570:
2020-03-27T18:51:26.5064121Z   vitess.io/vitess/go/vt/wrangler.newTestVDiffEnv()
2020-03-27T18:51:26.5064364Z       /home/runner/work/vitess/vitess/go/vt/wrangler/vdiff_env_test.go:169 +0x1671
2020-03-27T18:51:26.5064583Z   vitess.io/vitess/go/vt/wrangler.TestVDiffAggregates()
2020-03-27T18:51:26.5064819Z       /home/runner/work/vitess/vitess/go/vt/wrangler/vdiff_test.go:630 +0xde
2020-03-27T18:51:26.5064967Z   testing.tRunner()
2020-03-27T18:51:26.5065188Z       /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:909 +0x199
2020-03-27T18:51:26.5065283Z 
2020-03-27T18:51:26.5065447Z Goroutine 176 (running) created at:
2020-03-27T18:51:26.5065814Z   vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).AddTablet()
2020-03-27T18:51:26.5066079Z       /home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:769 +0x595
2020-03-27T18:51:26.5066747Z   vitess.io/vitess/go/vt/discovery.(*TopologyWatcher).loadTablets()
2020-03-27T18:51:26.5066998Z       /home/runner/work/vitess/vitess/go/vt/discovery/topology_watcher.go:259 +0xd87
2020-03-27T18:51:26.5068923Z   vitess.io/vitess/go/vt/discovery.(*TopologyWatcher).watch()
2020-03-27T18:51:26.5069219Z       /home/runner/work/vitess/vitess/go/vt/discovery/topology_watcher.go:168 +0xfc
2020-03-27T18:51:26.5069320Z 
2020-03-27T18:51:26.5069484Z Goroutine 570 (running) created at:
2020-03-27T18:51:26.5069638Z   testing.(*T).Run()
2020-03-27T18:51:26.5069844Z       /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:960 +0x651
2020-03-27T18:51:26.5070016Z   testing.runTests.func1()
2020-03-27T18:51:26.5070244Z       /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1202 +0xa6
2020-03-27T18:51:26.5070681Z   testing.tRunner()
2020-03-27T18:51:26.5070917Z       /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:909 +0x199
2020-03-27T18:51:26.5071243Z   testing.runTests()
2020-03-27T18:51:26.5071469Z       /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1200 +0x521
2020-03-27T18:51:26.5071632Z   testing.(*M).Run()
2020-03-27T18:51:26.5071857Z       /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1117 +0x2ff
2020-03-27T18:51:26.5072007Z   main.main()
2020-03-27T18:51:26.5072164Z       _testmain.go:218 +0x223
2020-03-27T18:51:26.5072297Z ==================
2020-03-27T18:51:26.5072441Z ==================
2020-03-27T18:51:26.5072585Z WARNING: DATA RACE
2020-03-27T18:51:26.5072763Z Write at 0x00c000bde9f0 by goroutine 176:
2020-03-27T18:51:26.5072936Z   sync/atomic.CompareAndSwapInt32()
2020-03-27T18:51:26.5073167Z       /opt/hostedtoolcache/go/1.13.9/x64/src/runtime/race_amd64.s:293 +0xb
2020-03-27T18:51:26.5073329Z   sync.(*Mutex).Lock()
2020-03-27T18:51:26.5073543Z       /opt/hostedtoolcache/go/1.13.9/x64/src/sync/mutex.go:74 +0x49
2020-03-27T18:51:26.5073744Z   vitess.io/vitess/go/vt/wrangler.init.1.func1()
2020-03-27T18:51:26.5073986Z       /home/runner/work/vitess/vitess/go/vt/wrangler/vdiff_env_test.go:69 +0x78
2020-03-27T18:51:26.5074195Z   vitess.io/vitess/go/vt/discovery.(*healthCheckConn).stream()
2020-03-27T18:51:26.5074439Z       /home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:614 +0x55f
2020-03-27T18:51:26.5074664Z   vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).checkConn()
2020-03-27T18:51:26.5074903Z       /home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:545 +0x496
2020-03-27T18:51:26.5074998Z 
2020-03-27T18:51:26.5075187Z Previous write at 0x00c000bde9f0 by goroutine 570:
2020-03-27T18:51:26.5075357Z   [failed to restore the stack]
2020-03-27T18:51:26.5075424Z 
2020-03-27T18:51:26.5075587Z Goroutine 176 (running) created at:
2020-03-27T18:51:26.5076296Z   vitess.io/vitess/go/vt/discovery.(*HealthCheckImpl).AddTablet()
2020-03-27T18:51:26.5076786Z       /home/runner/work/vitess/vitess/go/vt/discovery/healthcheck.go:769 +0x595
2020-03-27T18:51:26.5077438Z   vitess.io/vitess/go/vt/discovery.(*TopologyWatcher).loadTablets()
2020-03-27T18:51:26.5077712Z       /home/runner/work/vitess/vitess/go/vt/discovery/topology_watcher.go:259 +0xd87
2020-03-27T18:51:26.5077939Z   vitess.io/vitess/go/vt/discovery.(*TopologyWatcher).watch()
2020-03-27T18:51:26.5078171Z       /home/runner/work/vitess/vitess/go/vt/discovery/topology_watcher.go:168 +0xfc
2020-03-27T18:51:26.5078270Z 
2020-03-27T18:51:26.5078434Z Goroutine 570 (running) created at:
2020-03-27T18:51:26.5078586Z   testing.(*T).Run()
2020-03-27T18:51:26.5078810Z       /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:960 +0x651
2020-03-27T18:51:26.5078977Z   testing.runTests.func1()
2020-03-27T18:51:26.5079187Z       /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1202 +0xa6
2020-03-27T18:51:26.5079749Z   testing.tRunner()
2020-03-27T18:51:26.5079996Z       /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:909 +0x199
2020-03-27T18:51:26.5080299Z   testing.runTests()
2020-03-27T18:51:26.5080547Z       /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1200 +0x521
2020-03-27T18:51:26.5080715Z   testing.(*M).Run()
2020-03-27T18:51:26.5080938Z       /opt/hostedtoolcache/go/1.13.9/x64/src/testing/testing.go:1117 +0x2ff
2020-03-27T18:51:26.5081089Z   main.main()
2020-03-27T18:51:26.5081244Z       _testmain.go:218 +0x223
2020-03-27T18:51:26.5081393Z ==================
```

**Comment by GuptaManan100** [comment] 2020-12-01 06:18
Duplicate of #5997

**Closed** 2020-12-01 06:19 UTC
Labels: Status: Duplicate, Type: Bug
