### ISSUE TITLE
"use database" handling in mysql CLI client broken

### ISSUE THREAD

**Issue by aquarapid** [vitessio/vitess#5206] opened 2019-09-19 21:26 UTC
The mysql CLI client transforms commands of the form:   "USE database1" to a COM_INIT_DB MySQL RPC against the server.

However, I suspect a recent change (#5136) broke this handling.  The result is that issuing a "USE keyspace1" request against vtgate will succeed and have the desired result the first time, but thereafter, "USE keyspace2" will seem to succeed, but not actually change the keyspace/DB context.

Using a client (e.g. the python MySQLdb module) that does not issue COM_INIT_DB, and insteads sends "USE keyspaceX" as a query, seems to still work properly.

**Comment by morgo** [comment] 2019-09-19 23:46
Most clients use `COM_INIT_DB`, but JDBC for example will issue the SQL command `USE database`. I will add this to client features tracking..

**Comment by parthibd** [comment] 2019-09-28 17:49
If this issue is fixed, we can close this issue.

**Comment by tirsen** [comment] 2019-10-02 23:46
`COM_INIT_DB` only works once? Is it easy to write a test that reproduces this?

Is this because there’s a mismatch with the connection.SchemaName and session.TargetString and we need to do more to make them match up? Or even better, we get rid of one of them?

**Closed** 2019-11-03 17:22 UTC
Labels: P1, Type: Bug
