### ISSUE TITLE
Bug Report: running with 101_init_cluster.yaml, replica vttablet pod terminating again and again

### ISSUE THREAD

**Issue by dk-lockdown** [vitessio/vitess#12507] opened 2023-02-28 12:41 UTC
### Overview of the Issue

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/33612882/221855622-71103314-7abb-4e1d-aec5-805fb052c98f.png">

vttablet log:
```
I0228 11:26:10.605433       1 query.go:81] exec CHANGE MASTER TO
  MASTER_HOST = '21.100.65.118',
  MASTER_PORT = 3306,
  MASTER_USER = 'vt_repl',
  MASTER_PASSWORD = '****',
  MASTER_CONNECT_RETRY = 10,
  MASTER_AUTO_POSITION = 1
I0228 11:26:10.616384       1 query.go:81] exec START SLAVE
I0228 11:26:10.624291       1 rpc_replication.go:710] Set up MySQL replication; should now be replicating from cell:"zone1" uid:2469782763 at
I0228 11:26:10.624361       1 rpc_server.go:84] TabletManager.SetReplicationSource(parent:{cell:"zone1" uid:2469782763} force_start_replication:true)(on zone1-2548885007 from ): (*tabletmanagerdata.SetReplicationSourceResponse)(nil)
I0228 11:26:13.040329       1 state_manager.go:687] Replication is healthy
I0228 11:26:44.872628       1 run.go:61] Entering lameduck mode for at least 50ms
I0228 11:26:44.872652       1 run.go:62] Firing asynchronous OnTerm hooks
I0228 11:26:44.872665       1 servenv.go:222] Firing OnTermSync hooks and waiting up to 10s for them
I0228 11:26:44.872695       1 grpc_server.go:306] Initiated graceful stop of gRPC server
I0228 11:26:44.872737       1 grpc_server.go:308] gRPC server stopped
I0228 11:26:44.872744       1 servenv.go:235] OnTermSync hooks finished
I0228 11:26:44.872749       1 run.go:67] Sleeping an extra 49.87303ms after OnTermSync to finish lameduck period
I0228 11:26:44.872781       1 updatestreamctl.go:243] Update Stream Disabled
I0228 11:26:44.923012       1 run.go:71] Shutting down gracefully
```

mysqld log:
```
I0228 12:35:50.212770       1 grpc_server.go:209] Setting grpc max message size to 16777216
I0228 12:35:50.212807       1 grpc_server.go:384] Building interceptors with 0 unary interceptors and 0 stream interceptors
I0228 12:35:50.212874       1 service_map.go:66] Registering mysqlctl for grpc, disable it with -grpc-mysqlctl service_map parameter
I0228 12:35:50.213926       1 unix_socket.go:54] Listening on socket file /vt/socket/mysqlctl.sock for gRPC
I0228 12:35:52.731983       1 mysqld.go:425] Mysqld.Start(1677587749) stderr: 2023-02-28T12:35:52.731892Z 27 [System] [MY-010597] [Repl] 'CHANGE MASTER TO FOR CHANNEL '' executed'. Previous state master_host='', master_port= 3306, master_log_file='', master_log_pos= 4, master_bind=''. New state master_host='21.100.65.131', master_port= 3306, master_log_file='', master_log_pos= 4, master_bind=''.
I0228 12:35:52.737508       1 mysqld.go:425] Mysqld.Start(1677587749) stderr: 2023-02-28T12:35:52.737392Z 34 [Warning] [MY-010897] [Repl] Storing MySQL user name or password information in the master info repository is not secure and is therefore not recommended. Please consider using the USER and PASSWORD connection options for START SLAVE; see the 'START SLAVE Syntax' in the MySQL Manual for more information.
I0228 12:35:52.741124       1 mysqld.go:425] Mysqld.Start(1677587749) stderr: 2023-02-28T12:35:52.741032Z 34 [System] [MY-010562] [Repl] Slave I/O thread for channel '': connected to master 'vt_repl@21.100.65.131:3306',replication started in log 'FIRST' at position 4
I0228 12:36:28.063413       1 run.go:61] Entering lameduck mode for at least 50ms
I0228 12:36:28.063446       1 run.go:62] Firing asynchronous OnTerm hooks
I0228 12:36:28.063460       1 servenv.go:222] Firing OnTermSync hooks and waiting up to 10s for them
I0228 12:36:28.063518       1 mysqlctld.go:139] mysqlctl received SIGTERM, shutting down mysqld first
I0228 12:36:28.063525       1 mysqld.go:513] Mysqld.Shutdown
I0228 12:36:28.063563       1 mysqld.go:551] No mysqld_shutdown hook, running mysqladmin directly
I0228 12:36:28.063935       1 mysqld.go:617] execCmd: /usr/bin/mysqladmin /usr/bin/mysqladmin [--defaults-extra-file=/tmp/example2398069843 --shutdown-timeout=300 --connect-timeout=30 --wait=10 shutdown]
I0228 12:36:28.071497       1 mysqld.go:425] Mysqld.Start(1677587749) stderr: 2023-02-28T12:36:28.071219Z 58 [System] [MY-013172] [Server] Received SHUTDOWN from user vt_dba. Shutting down mysqld (Version: 8.0.31).
I0228 12:36:30.075895       1 mysqld.go:425] Mysqld.Start(1677587749) stderr: 2023-02-28T12:36:30.075795Z 0 [Warning] [MY-010909] [Server] /usr/sbin/mysqld: Forcing close of thread 32  user: 'vt_dba'.
```

### Reproduction Steps

kubectl apply -f 101_init_cluster.yaml

### Binary Version

```sh
Version: 16.0.0-SNAPSHOT (Git revision e596c1d9c8dd4b1267e6fc2865c2e561e34020fc branch 'main') built on Fri Feb  3 00:36:15 UTC 2023 by vitess@buildkitsandbox using go1.19.4 linux/amd64
```

### Operating System and Environment details

```sh
k8s v1.22.5
centos 9
```

**Comment by mattlord** [comment] 2023-03-01 00:41
Hi @dk-lockdown,

This is not a bug report AFAICT, but rather a request for support/help. For things like this, you should use the [Vitess Slack](https://vitess.io/community/) so that the community (which includes the project maintainers) can help — these kinds of things often take a lot of back and forth as each k8s cluster is a snowflake and this is not a good venue for support. 

I don't know if you have followed the guide here or not (e.g. using `minikube` with 8000MiB of memory): https://vitess.io/docs/16.0/get-started/operator/

All I can tell you from what was provided is that it looks like k8s is terminating the pod, most likely because there aren't enough resources available (I would guess memory). You would have to look at the system events and logs to see for sure.

I'm going to close this for now, please bring this up in the `#general` channel there if you need more help.

I you feel that I'm mistaken and there is a bug here, please provide additional information such as a repeatable test case that demonstrates the bug.

Thanks!

**Closed by mattlord** 2023-03-01 00:41 UTC
Labels: Status: Unable to Reproduce, Status: Need more Information, Component: Operator

**Comment by dk-lockdown** [comment] 2023-03-01 06:23
@mattlord sure, the pod is terminating by k8s, because readness probe failed, and i found the /vt/socket/mysql.sock was recreate again and again.
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/33612882/222060620-02927d70-fae1-4a7c-8e20-32229b02b99c.png">
