### ISSUE TITLE
Flaky TestPlayerIdleUpdate test

### ISSUE THREAD

**Issue by ajm188** [vitessio/vitess#8323] opened 2021-06-13 23:33 UTC
```
--- FAIL: TestPlayerIdleUpdate (0.14s)
Error:     vplayer_flaky_test.go:1900: query:
        "update _vt.vreplication set pos='MySQL56/6f566dda-cc97-11eb-a30c-000d3aff91e3:1-897', time_updated=1623623653, transaction_timestamp=1623623653, rows_copied=0, message='' where id=45", does not match query 0:
        "begin"
Error:     vplayer_flaky_test.go:1900: query:
        "begin", does not match query 1:
        "insert into t1(id,val) values (1,'aaa')"
Error:     vplayer_flaky_test.go:1900: query:
        "insert into t1(id,val) values (1,'aaa')", does not match query 2:
        "/update _vt.vreplication set pos="
Error:     vplayer_flaky_test.go:1900: query:
        "update _vt.vreplication set pos='MySQL56/6f566dda-cc97-11eb-a30c-000d3aff91e3:1-902', time_updated=1623623653, transaction_timestamp=1623623653, rows_copied=0, message='' where id=45", does not match query 3:
        "commit"
Error:     vplayer_flaky_test.go:1911: query:
        "commit", does not match query 0:
        "/update _vt.vreplication set pos="
E0613 22:34:20.451543   32307 vreplicator.go:148] Replicate error: vstream ended
E0613 22:34:20.452607   32307 controller.go:163] stream 52: vstream ended, retrying after 1ms
FAIL
FAIL	vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication	28.481s
FAIL
```

Logs before the failure:

```
E0613 23:18:56.375369   32587 query.go:83] ExecuteFetch(ALTER TABLE _vt.vreplication ADD COLUMN db_name VARBINARY(255) NOT NULL) failed: Duplicate column name 'db_name' (errno 1060) (sqlstate 42S21) during query: ALTER TABLE _vt.vreplication ADD COLUMN db_name VARBINARY(255) NOT NULL
E0613 23:18:56.424948   32587 binlog_player.go:242] error (expected error) in selecting vreplication settings select pos, stop_pos, max_tps, max_replication_lag, state from _vt.vreplication where id=1
E0613 23:18:56.425221   32587 controller.go:163] stream 1: error (expected error) in selecting vreplication settings select pos, stop_pos, max_tps, max_replication_lag, state from _vt.vreplication where id=1, retrying after 10ms
W0613 23:18:56.444550   32587 controller.go:159] context canceled: context has expired
E0613 23:18:56.445650   32587 engine.go:224] Error starting vreplication engine: err, will keep retrying.
E0613 23:18:56.466704   32587 engine.go:224] Error starting vreplication engine: err, will keep retrying.
E0613 23:18:56.466814   32587 engine.go:224] Error starting vreplication engine: err, will keep retrying.
E0613 23:18:56.492452   32587 engine.go:742] error waiting for pos: MariaDB/0-1-1084, last pos: MariaDB/0-1-1083: context canceled, wait time: 87.7µs: possibly no tablets are available to stream in the source keyspace for your cell and tablet_types setting
E0613 23:19:10.325604   32587 vplayer.go:399] Error applying event: filter rules are not supported for SBR replication: [match:"dst1" filter:"select * from src1"]
E0613 23:19:10.326290   32587 vreplicator.go:148] Replicate error: filter rules are not supported for SBR replication: [match:"dst1" filter:"select * from src1"]
E0613 23:19:10.327115   32587 controller.go:163] stream 31: filter rules are not supported for SBR replication: [match:"dst1" filter:"select * from src1"], retrying after 5s
W0613 23:19:10.328141   32587 controller.go:168] context canceled: filter rules are not supported for SBR replication: [match:"dst1" filter:"select * from src1"]
E0613 23:19:11.261911   32587 vplayer_flaky_test.go:1310] TestPlayerTypes: flavor is MySQL56
W0613 23:19:11.261997   32587 vplayer_flaky_test.go:1319] Not running JSON column type tests on flavor mysql56
E0613 23:19:11.805794   32587 vplayer_flaky_test.go:1535] Expected log:: TestPlayerDDL Positions are: before first alter MySQL56/b84b9c99-cc9d-11eb-9dd1-000d3a6e5295:1-815, after first alter MySQL56/b84b9c99-cc9d-11eb-9dd1-000d3a6e5295:1-816, before second alter MySQL56/b84b9c99-cc9d-11eb-9dd1-000d3a6e5295:1-817, after second alter MySQL56/b84b9c99-cc9d-11eb-9dd1-000d3a6e5295:1-818
E0613 23:19:12.148600   32587 vplayer.go:399] Error applying event: Duplicate column name 'val2' (errno 1060) (sqlstate 42S21) during query: alter table t1 add column val2 varchar(128)
E0613 23:19:12.149487   32587 vreplicator.go:148] Replicate error: Duplicate column name 'val2' (errno 1060) (sqlstate 42S21) during query: alter table t1 add column val2 varchar(128)
E0613 23:19:12.150667   32587 controller.go:163] stream 42: Duplicate column name 'val2' (errno 1060) (sqlstate 42S21) during query: alter table t1 add column val2 varchar(128), retrying after 5s
W0613 23:19:12.151170   32587 controller.go:168] context canceled: Duplicate column name 'val2' (errno 1060) (sqlstate 42S21) during query: alter table t1 add column val2 varchar(128)
```

**Comment by ajm188** [comment] 2021-06-13 23:36
Example failed check: https://github.com/vitessio/vitess/pull/8232/checks?check_run_id=2815510293

**Comment by shlomi-noach** [comment] 2021-06-15 09:12
```
E0615 09:08:15.761134    1453 query.go:83] ExecuteFetch(ALTER TABLE _vt.vreplication ADD COLUMN db_name VARBINARY(255) NOT NULL) failed: Duplicate column name 'db_name' (errno 1060) (sqlstate 42S21) during query: ALTER TABLE _vt.vreplication ADD COLUMN db_name VARBINARY(255) NOT NULL
E0615 09:08:15.809602    1453 binlog_player.go:242] error (expected error) in selecting vreplication settings select pos, stop_pos, max_tps, max_replication_lag, state from _vt.vreplication where id=1
E0615 09:08:15.809822    1453 controller.go:163] stream 1: error (expected error) in selecting vreplication settings select pos, stop_pos, max_tps, max_replication_lag, state from _vt.vreplication where id=1, retrying after 10ms
E0615 09:08:15.828643    1453 engine.go:227] Error starting vreplication engine: err, will keep retrying.
E0615 09:08:15.859601    1453 engine.go:227] Error starting vreplication engine: err, will keep retrying.
E0615 09:08:15.859771    1453 engine.go:227] Error starting vreplication engine: err, will keep retrying.
E0615 09:08:15.887866    1453 engine.go:745] error waiting for pos: MariaDB/0-1-1084, last pos: MariaDB/0-1-1083: context canceled, wait time: 71.403µs: possibly no tablets are available to stream in the source keyspace for your cell and tablet_types setting
E0615 09:08:29.695067    1453 vplayer.go:399] Error applying event: filter rules are not supported for SBR replication: [match:"dst1" filter:"select * from src1"]
E0615 09:08:29.695824    1453 vreplicator.go:148] Replicate error: filter rules are not supported for SBR replication: [match:"dst1" filter:"select * from src1"]
E0615 09:08:29.696904    1453 controller.go:163] stream 31: filter rules are not supported for SBR replication: [match:"dst1" filter:"select * from src1"], retrying after 5s
W0615 09:08:29.697578    1453 controller.go:168] context canceled: filter rules are not supported for SBR replication: [match:"dst1" filter:"select * from src1"]
E0615 09:08:30.631887    1453 vplayer_flaky_test.go:1310] TestPlayerTypes: flavor is MySQL56
W0615 09:08:30.631964    1453 vplayer_flaky_test.go:1319] Not running JSON column type tests on flavor mysql56
E0615 09:08:31.134483    1453 vplayer_flaky_test.go:1535] Expected log:: TestPlayerDDL Positions are: before first alter MySQL56/3682a010-cdb9-11eb-847f-000d3a0430af:1-813, after first alter MySQL56/3682a010-cdb9-11eb-847f-000d3a0430af:1-815, before second alter MySQL56/3682a010-cdb9-11eb-847f-000d3a0430af:1-816, after second alter MySQL56/3682a010-cdb9-11eb-847f-000d3a0430af:1-817
E0615 09:08:31.462283    1453 vplayer.go:399] Error applying event: Duplicate column name 'val2' (errno 1060) (sqlstate 42S21) during query: alter table t1 add column val2 varchar(128)
E0615 09:08:31.463268    1453 vreplicator.go:148] Replicate error: Duplicate column name 'val2' (errno 1060) (sqlstate 42S21) during query: alter table t1 add column val2 varchar(128)
E0615 09:08:31.465478    1453 controller.go:163] stream 42: Duplicate column name 'val2' (errno 1060) (sqlstate 42S21) during query: alter table t1 add column val2 varchar(128), retrying after 5s
W0615 09:08:31.465839    1453 controller.go:168] context canceled: Duplicate column name 'val2' (errno 1060) (sqlstate 42S21) during query: alter table t1 add column val2 varchar(128)
--- FAIL: TestPlayerIdleUpdate (0.15s)
Error:     vplayer_flaky_test.go:1900: query:
        "update _vt.vreplication set pos='MySQL56/3682a010-cdb9-11eb-847f-000d3a0430af:1-899', time_updated=1623748112, transaction_timestamp=1623748112, rows_copied=0, message='' where id=45", does not match query 0:
        "begin"
Error:     vplayer_flaky_test.go:1900: query:
        "begin", does not match query 1:
        "insert into t1(id,val) values (1,'aaa')"
Error:     vplayer_flaky_test.go:1900: query:
        "insert into t1(id,val) values (1,'aaa')", does not match query 2:
        "/update _vt.vreplication set pos="
Error:     vplayer_flaky_test.go:1900: query:
        "update _vt.vreplication set pos='MySQL56/3682a010-cdb9-11eb-847f-000d3a0430af:1-904', time_updated=1623748112, transaction_timestamp=1623748112, rows_copied=0, message='' where id=45", does not match query 3:
        "commit"
Error:     vplayer_flaky_test.go:1911: query:
        "commit", does not match query 0:
        "/update _vt.vreplication set pos="
E0615 09:08:39.368672    1453 vreplicator.go:148] Replicate error: vstream ended
E0615 09:08:39.369687    1453 controller.go:163] stream 52: vstream ended, retrying after 1ms
FAIL
FAIL	vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication	28.725s
```

**Comment by shlomi-noach** [comment] 2021-06-15 09:12
Not sure I'm the right person to be assigned -- I'll give it a shot.

**Comment by rohit-nayak-ps** [comment] 2021-06-15 09:21
Are you able to reproduce this locally? I tried multiple times, but it works fine on main on my setup. 

Looks like an extra pos update (possibly due to an heartbeat) is leftover from a previous test.

**Comment by shlomi-noach** [comment] 2021-06-15 09:31
> Looks like an extra pos update (possibly due to an heartbeat) is leftover from a previous test.

Yeah, looks like that! It's always one query that pushes everything else down. No, I haven't been able to reproduce locally.

**Comment by shlomi-noach** [comment] 2021-06-15 09:56
Heuristic solution offered in https://github.com/vitessio/vitess/pull/8339. Can't say it's a _good_ solution, and let's see how goes.

I think this issue here iterates back on an earlier discussion: we should run an actual MySQL server in the backend, instead of mockup, and the unit test should check for _actual data_ in the database, rather than look for an expected sequence of queries sent to the server.

I've volunteered to do just that a couple months ago, but never got round to doing it.

**Comment by shlomi-noach** [comment] 2021-06-16 05:29
#8339 seems to have done the job. Closing for now.

**Closed by shlomi-noach** 2021-06-16 05:29 UTC
Labels: Component: Build/CI, Type: CI/Build
