### ISSUE TITLE
101_initial_cluster Failed to load slave replication state

### ISSUE THREAD

**Issue by fayak** [vitessio/vitess#5418] opened 2019-11-07 14:33 UTC
#### Overview of the Issue

While running ./101_initial_cluster.sh after a fresh install, following the documentation on https://vitess.io/docs/get-started/local/, I get those errors:

```
root@vitess:~/vitess/examples/local# ./101_initial_cluster.sh 
enter etcd2 env
add /vitess/global
add /vitess/zone1
add zone1 CellInfo
etcd start done...
enter etcd2 env
Starting vtctld...
Access vtctld web UI at http://vitess:15000
Send commands with: vtctlclient -server vitess:15999 ...
enter etcd2 env
Starting MySQL for tablet zone1-0000000100...
Starting MySQL for tablet zone1-0000000101...
Starting MySQL for tablet zone1-0000000102...
E1107 15:20:29.279179    2473 mysqld.go:665] failed starting mysqld in time: deadline exceeded waiting for mysqld socket file to appear: /root/vtdataroot/vt_0000000102/mysql.sock
tail of mysql error log (/root/vtdataroot/vt_0000000102/error.log):
2019-11-07 15:15:29 6 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1017: Can't find file: './mysql/' (errno: 2 "No such file or directory")
E1107 15:20:29.279361    2473 mysqlctl.go:254] failed init mysql: deadline exceeded waiting for mysqld socket file to appear: /root/vtdataroot/vt_0000000102/mysql.sock
E1107 15:20:29.334756    2472 mysqld.go:665] failed starting mysqld in time: deadline exceeded waiting for mysqld socket file to appear: /root/vtdataroot/vt_0000000101/mysql.sock
tail of mysql error log (/root/vtdataroot/vt_0000000101/error.log):
2019-11-07 15:15:29 6 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1017: Can't find file: './mysql/' (errno: 2 "No such file or directory")
E1107 15:20:29.334933    2472 mysqlctl.go:254] failed init mysql: deadline exceeded waiting for mysqld socket file to appear: /root/vtdataroot/vt_0000000101/mysql.sock
E1107 15:20:29.498964    2471 mysqld.go:665] failed starting mysqld in time: deadline exceeded waiting for mysqld socket file to appear: /root/vtdataroot/vt_0000000100/mysql.sock
tail of mysql error log (/root/vtdataroot/vt_0000000100/error.log):
2019-11-07 15:15:29 6 [Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1017: Can't find file: './mysql/' (errno: 2 "No such file or directory")
E1107 15:20:29.499115    2471 mysqlctl.go:254] failed init mysql: deadline exceeded waiting for mysqld socket file to appear: /root/vtdataroot/vt_0000000100/mysql.sock
Starting vttablet for zone1-0000000100...
Access tablet zone1-0000000100 at http://vitess:15100/debug/status
Starting vttablet for zone1-0000000101...
Access tablet zone1-0000000101 at http://vitess:15101/debug/status
Starting vttablet for zone1-0000000102...
Access tablet zone1-0000000102 at http://vitess:15102/debug/status
Waiting for tablets to be listening...
```

And it hangs forever

#### Reproduction Steps

Fresh install of Debian 10 in QEMU/KVM, follow the local instruction and run ./101_initial_cluster.sh

#### Binary version

Archive downloaded and extracted from https://github.com/vitessio/vitess/releases/download/v4.0.0/vitess-release-ad1f076.tar.gz

release 4.0.0

#### Operating system and Environment details

```
$ uname -a
Linux vitess 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
$ apt install -y default-mysql-server default-mysql-client etcd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
etcd is already the newest version (3.2.26+dfsg-3).
default-mysql-client is already the newest version (1.0.5).
default-mysql-server is already the newest version (1.0.5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

```
#### Log Fragments

cf 1st section

**Comment by deepthi** [comment] 2019-11-07 15:26
@morgo looks like it isn't able to find the mysql binary:
`Can't find file: './mysql/' (errno: 2 "No such file or directory")`

**Comment by fayak** [comment] 2019-11-07 16:11
```
~$ find -name mysql
./vitess/go/mysql
./vitess/java/client/src/main/java/io/vitess/mysql
./vitess/java/client/src/test/java/io/vitess/mysql

```

```

~$ find / -name mysql
/root/vitess/go/mysql
/root/vitess/java/client/src/main/java/io/vitess/mysql
/root/vitess/java/client/src/test/java/io/vitess/mysql
/etc/init.d/mysql
/etc/apparmor.d/abstractions/mysql
/etc/default/mysql
/etc/mysql
/usr/lib/x86_64-linux-gnu/perl5/5.28/DBD/mysql
/usr/lib/x86_64-linux-gnu/perl5/5.28/auto/DBD/mysql
/usr/share/bash-completion/completions/mysql
/usr/share/mysql
/usr/bin/mysql
/var/log/mysql
/var/lib/mysql
/var/lib/mysql/mysql
```

I don't know how useful this could be

**Comment by morgo** [comment] 2019-11-07 16:13
I can see that MySQL is found - one of the errors is generated by MySQL. I am going to try and reproduce now, and I might ask you for more info if required.

**Comment by morgo** [comment] 2019-11-07 16:14
nvm, I figured it out! You are running the script as `root`. This is not supported by MySQL, but the error in the log is being truncated (it should be written to screen).

If you try again on the same instance, make sure that you delete the VTDATAROOT, because there will be permission errors.

**Comment by morgo** [comment] 2019-11-09 20:24
Thank you for reporting this issue.

Stronger protection against running as root has been merged to master. It will still be present in 4.0.0 as this build is already out there, but should be made clearer for other users in future.

I am going to close this issue for now.

**Closed by morgo** 2019-11-09 20:24 UTC
Labels: Type: Question
